### PR TITLE
peer sorting implementation

### PR DESCRIPTION
**Pull request by NicKoehler**
I'm not a flutter expert, but I implemented the sorting feature #2948, it probably needs some design improvements, but the feature is here:

- [x] desktop
- [x] mobile
- [x] save user preference once selected
- [x] not visible in "recent sessions"
- [x] rounded tiles
- [x] unify peer view modes in one button
- [x] find better design/positioning

I'm sure there are some improvements to be made. I'm open to any suggestion, feel free to let me know if you need code changes.

| Desktop | Mobile |
| -- | -- |
| image |image |

### CODE REVIEW

**Comment by NicKoehler** [comment]
@rustdesk sorry for bothering you again for build errors, but I'm trying to run this pr on a real arm64 mobile device without success.

I build rustdesk with: `cargo build --lib --features flutter` but when I run flutter I receive:

```
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:42985/BIlrmkiYR5w=/ws
I/flutter (29779): launch args: []
I/flutter (29779): initializing FFI main
I/flutter (29779): initialize failed: Invalid argument(s): Failed to lookup symbol 'session_register_texture': undefined symbol: session_register_texture
```

**Comment by rustdesk** [comment]
You do not need to build rust yourself,  https://github.com/rustdesk/rustdesk/issues/3262#issuecomment-1445285288

**Comment by rustdesk** [comment]
Building rust for android is different from desktop.
 https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-nightly.yml#L499

**Comment by rustdesk** [comment]
@NicKoehler can we find a better place to put the dropbox? @grummbeer do you have any idea about this?

**Comment by rustdesk** [comment]
Find a icon, and put it on the right side of "gird/tile" icon?

**Comment by NicKoehler** [comment]
I'll try this

> Find a icon, and put it on the right side of "gird/tile"

**Comment by grummbeer** [comment]
>  no need to waste place there.

Not on desktop, but on mobile the space is already very limited, some kind of second row or other arrangement of the elements might be relevant in the future. On mobile you can't slide the tabs (results in drag/drop) and it is not easy to hit the tiny arrows with fat fingers like mine

**Comment by rustdesk** [comment]
need a better icon telling it is sorting.

**Comment by NicKoehler** [comment]
What do you think about this one?

image

**Comment by rustdesk** [comment]
i like this one https://www.flaticon.com/free-icon/sort-by-attributes_25321?term=sort&page=1&position=17&origin=tag&related_id=25321

**Comment by rustdesk** [comment]
can you also add sorting by host name? Be noted, the id can be alias also.

**Comment by rustdesk** [comment]
no √ sign after selected?

**Comment by NicKoehler** [comment]
> no √ sign after selected?

I added radio elements, do you prefer √ ?

Also check out if you like this icon, if you want the one you posted I'll use an svg asset.

image

**Comment by rustdesk** [comment]
radio is fine

**Comment by rustdesk** [comment]
there is conflict.

**Comment by NicKoehler** [comment]
Conflicts solved. Tell me if there's anything else that you think it needs to be changed

**Comment by grummbeer** [comment]
Overflow, may depend on longer words in languages other than en.

sort-by-overflow

Is there a specifc reason for having now three different looking pulldown menus (menubar, peer three-dot-menu, sort by)?

**Comment by rustdesk** [comment]
i modified from 5 to 3

**Comment by rustdesk** [comment]
flutter overflow is super annoying

**Pull request merged**
