### PR TITLE
Feat single peer per row/list view

### PR DESCRIPTION
**Pull request by beelchester**
https://github.com/rustdesk/rustdesk/discussions/4731
New peer view option: 'List'
Updated other view type names to 'Big Tiles' & 'Small Tiles'

(old video)

https://github.com/rustdesk/rustdesk/assets/73148455/c9fd3aaf-9746-41fd-a014-a7f9cd7cd25c

(updated video)

https://github.com/rustdesk/rustdesk/assets/73148455/a9f223fd-33e6-43ec-87f6-1a2d49b513f8

In case of long alias name:
Screenshot 2023-10-24 at 11 27 23 PM

### CODE REVIEW

**Comment by sahilyeole** [comment]
Group tab:

Screenshot 2023-10-25 at 1 27 03 AM

**Comment by rustdesk** [comment]
A little wierd, the behavior of clicking on 
image

**Comment by rustdesk** [comment]
It is ok when there are only two styles, can switch with clicking, but now, there are three, switching by clicking on is not appropriate, not a common UI language.

**Comment by rustdesk** [comment]
Please change to dropdown

**Comment by sahilyeole** [comment]
Dropdown menu added:

https://github.com/rustdesk/rustdesk/assets/73148455/a9f223fd-33e6-43ec-87f6-1a2d49b513f8

**Comment by rustdesk** [comment]
Unified to this style, https://github.com/rustdesk/rustdesk/commit/0fe80e8e1f244a134423f5b2409e05635bb5c842

@21pages

**Comment by rustdesk** [comment]
bug: https://github.com/rustdesk/rustdesk/issues/6234

**Comment by sahilyeole** [comment]
Just checked on macos, the dropdown is working only on trackpad's soft touch, on clicking it is not working.
On other OS no problem with mouse click.
Not sure why, I'm working on fixing it.

**Comment by rustdesk** [comment]
Why? Does this dropdown work?

image

**Comment by sahilyeole** [comment]
Yes, sort by drop down is working but not the change view. Although, I've made it similar to sort by. I will get it fixed soon.

**Pull request merged**
