### PR TITLE
Update lv.rs

### PR DESCRIPTION
**Pull request by Kleofass**

### CODE REVIEW

**Comment by rustdesk** [comment]
How do you translate "public key", "secret key" in lv? https://en.wikipedia.org/wiki/Public-key_cryptography

**Comment by rustdesk** [comment]
https://lv.wikipedia.org/wiki/Publisk%C4%81s_atsl%C4%93gas_kriptogr%C4%81fija

**Comment by Kleofass** [comment]
> "public key", "secret key"
"publiskā atslēga", "slepenā atslēga"

**Comment by rustdesk** [comment]
but `atslēgas` is used in wikipedia.

**Comment by Kleofass** [comment]
"atslēgas" = "keys" are in majority format.

**Comment by rustdesk** [comment]
A lot of `s` here, interesting.

image

**Comment by Kleofass** [comment]
Direct translation. You can of course remove the word "server" to shorten it.
Network_english

**Pull request closed without merging**
