### PR TITLE
Remove existing /opt/artifacts/vcpkg in sciter builds

### PR DESCRIPTION
**Pull request by basilgello**
Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>

### CODE REVIEW

**Comment by rustdesk** [comment]
still not work

**Comment by basilgello** [comment]
```
Downloading vcpkg tool sources 
Building vcpkg-tool...
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.15...3.24 or higher is required.  You are running version 3.10.2
```

Let me find cmake 3.15+ for bionic armhf

**Comment by basilgello** [comment]
x86_64 linux sciter uses prebuilt CMake from Kitware but only aarch64 is built by them. Need to understand how do they build it. I know 3.16 can be built for 18.04 but we need 3.28 or newer

**Comment by basilgello** [comment]
I got access to arm64 runner and solving the issue with sciter

**Pull request merged**
