### PR TITLE
Fix ios draggable chat window

### PR DESCRIPTION
**Pull request by beelchester**
Also confirmed dark mode theme and automatic pop-up of chat window on receiving a message.

https://github.com/rustdesk/rustdesk/assets/73148455/331f30df-6ffa-4fd9-8905-08b2c0899840

(That lag while dragging is most likely because of running on the simulator)

### CODE REVIEW

**Comment by rustdesk** [comment]
Android tested？

**Comment by rustdesk** [comment]
if popped up automatically when receiving msg?

**Comment by sahilyeole** [comment]
> Android tested?

Done, it works the same as earlier. No issue.

Screenshot 2023-09-02 at 3 38 37 AM

**Comment by sahilyeole** [comment]
> if popped up automatically when receiving msg?

Yes, it works.

**Comment by rustdesk** [comment]
Some problems
- [ ] no border (android has border)
- [ ] position not remembered after moved (android also has this problem)
- [ ] the input is overlapped by the soft keyboard, the chat window can not automatically moving up when the soft keyboard pop out (this is the standard behavior for mobile).

**Comment by sahilyeole** [comment]
Ok, I'm on it.

**Comment by rustdesk** [comment]
Work on master branch for these.

**Comment by rustdesk** [comment]
I will merge to master soon.

**Comment by sahilyeole** [comment]
Tracking progress here:
- [ ] Bottom gap issue (ios)
- [ ] Add border (ios)
- [ ] Remember the last position (ios + android)
- [ ] Move up chat window on soft keyboard (ios)

**Pull request merged**
