### PR TITLE
Enable reading ID from CLI

### PR DESCRIPTION
**Pull request by Onyx47**
The patch allows you to read RustDesk ID from CLI if ran as a privileged user. Should solve #69 for most use cases.

### CODE REVIEW

**Comment by knro** [comment]
Thank you! This is highly needed for unattended deployments. I hope it gets merged soon!

**Comment by mooleshacat** [comment]
Badly needed, hope they start using cli arguments instead of putting everything in the filename which is pretty jenk if you ask me.

They also need configuration files that can be modified on Linux that at least has the ID inside it.

.config/rustdesk/RustDesk.toml only has an encrypted ID and no password which is useless to me.

**Comment by dinger1986** [comment]
What happens on linux if you use `--get-id` what version are you using? For password use `--password`

Configs used to not be encrypted but have moved to being encrypted

**Comment by grahamIT** [comment]
Is this documented anywhere?

**Comment by brunetton** [comment]
@rustdesk **why** don't you use something like [StructOpt](https://docs.rs/structopt/latest/structopt/) ?? No need to maintain any up-to-date separated documentation, the only documentation would be:

    for command line options, use `rustdesk --help`

That's all

**Comment by danielmarschall** [comment]
Is this also supported for the Windows Client (community edition)?
I tried everything, but I cannot get it to work.
I would love integrating RustDesk with my software, so I can open a connection with an ID and Password from the commandline.

**Comment by dinger1986** [comment]
hello, the client is the client whether used with an oss server or pro server.

You can use `--get-id | more` on windows or look at these scripts https://rustdesk.com/docs/en/self-host/client-deployment/

**Comment by danielmarschall** [comment]
`--get-id` does nothing for me. It just opens the normal window as if I had double clicked the EXE.

I want to automatically connect to a RustDesk client, like it is possible with TeamViewer and Anydesk.

Example: RustDesk is running on a remote machine with a permanent password.
I want to establish the connection via command-line,  e.g.  `RustDesk.exe --id 12345 --password foobar`
Is this possible?

**Comment by dinger1986** [comment]
You of course did use | more as well with the command as I wrote out?

Have you looked at the docs?

You'll see there's also integrations with other systems listed which would steer you on your way.

**Comment by danielmarschall** [comment]
Thank you for your reply. Yes, I have looked at the docs. I spent the whole day reading and searching the web and I cann't find any answers. I have setup everything, and even using my own RustDesk server. But for connecting using command line I did not find any working solution.

`rustdesk-1.2.2-x86_64.exe --get-id | more` shows:

```
skip .\....................
skip .\RustDeskIddDriver\RustDeskIddDriver.dll
skip .\RustDeskIddDriver\RustDeskIddDriver.inf
executing C:\Users\danie\AppData\Local\rustdesk\.\rustdesk.exe
Installation and administrative privileges required!

```

I have no idea what this does. I want to establish a connection. I do not want to install or deploy it. It is already deployed. I just want to start a connection without typing the number or password, just by clicking a batch file.

**Comment by dinger1986** [comment]
So you need to run that command elevated as previously said 👍

I linked to the deployment scripts cause they are setup to gather the info you are after and the other integrations show how they can be connected to.

**Comment by danielmarschall** [comment]
I know that I had to run it in elevanted command prompt. But I do not do it because IT IS already installed and deployed. I don't need to install something that is already installed.

Can you please link me to the doc of the integration? The only thing I can find is this https://rustdesk.com/docs/en/self-host/client-deployment/integrations/

**Comment by dinger1986** [comment]
to get the ID you need to run `rustdesk.exe --get-id | more` in an elevated command prompt, it wont get it unless its elevated

yes, that link and look at the collector scripts etc

**Comment by danielmarschall** [comment]
Yes, I did look at all the scripts.

I am afraid you don't understand... The customer has a fully deployed RustDesk. They have an ID number and a permanent password. I know both ID and Password.

In my ticket software I want a "Connect" button which automatically establishes the connection to that customer. I will enter the ID and Password in the customer details.

**Comment by dinger1986** [comment]
ah lol, 

you can use this then https://rustdesk.com/docs/en/self-host/client-deployment/integrations/tactical-rmm/#rustdesk-url-action

`rustdesk://connection/new/{{RustDeskIDField}}?password={{RustDeskPasswordField}}`

**Comment by danielmarschall** [comment]
This worked! Thank you so much for your help and patience :)

**Comment by grahamIT** [comment]
> I know that I had to run it in elevanted command prompt. But I do not do it because IT IS already installed and deployed. I don't need to install something that is already installed.
> 
> Can you please link me to the doc of the integration? The only thing I can find is this https://rustdesk.com/docs/en/self-host/client-deployment/integrations/

https://rustdesk.com/docs/en/self-host/client-deployment/integrations/tactical-rmm/
https://docs.tacticalrmm.com/3rdparty_rustdesk/

**Pull request merged**
