### PR TITLE
vcpkg-deps fixes

### PR DESCRIPTION
**Pull request by basilgello**
Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>

### CODE REVIEW

**Comment by basilgello** [comment]
This should fix macos signing. And I am doing lib sciter build locally to see why rust toolchain does not like libvpx

**Comment by basilgello** [comment]
Found the mess in sciter :) Should be fixed now

**Comment by basilgello** [comment]
Well, it might be that scrap rlib is emitted as LLVM bitcode but fed into conventional `cc` linker. Last time there was a known architecture mismatch between libvpx and rest of build, linker complained pointing to `vpx_decoder.c.o` inside scrap rlib. This time, it complains on whole rlib. The same error message surfaced when LTO was used. Maybe using lld as linker helps.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3556#issuecomment-1804010109

**Pull request merged**
