### PR TITLE
Try to fix sciter-armhf build

### PR DESCRIPTION
**Pull request by basilgello**
* Bootstrap CMake 3.29.7 for ubuntu/bionic/armhf

* vcpkg executable now needs GCC 8 but all product binaries are still OK with GCC 7

* Remove res/vcpkg/linux.cmake

This change needs https://github.com/basilgello/cmake to be transferred to https://github.com/rustdesk-org

### CODE REVIEW

**Comment by basilgello** [comment]
@rustdesk Please fork https://github.com/basilgello/cmake to https://github.com/rustdesk-org and merge this PR and trigger flutter nightly build action.

**Comment by rustdesk** [comment]
please transfer to rustdesk, forking can not for your releases.

**Comment by basilgello** [comment]
Moment, I have never tried transferring :)

**Comment by basilgello** [comment]
You don’t have the permission to create public repositories on rustdesk-org

**Comment by basilgello** [comment]
Please grant the permission temporary, and revoke it after you approve the transfer

**Comment by rustdesk** [comment]
rustdesk

**Comment by rustdesk** [comment]
can not compile cmake in CI?

**Comment by basilgello** [comment]
OK, transfer requested

**Comment by basilgello** [comment]
We can - instruction is in the repo

**Comment by rustdesk** [comment]
> We can - instruction is in the repo

Then we can add to CI in https://github.com/basilgello/cmake, or in rustdesk repo.

**Comment by rustdesk** [comment]
I have compile cmake before, it does not require very long time.

**Comment by basilgello** [comment]
Should I add CMake compile step to build-linux-sciter step or use artifact download?

**Comment by rustdesk** [comment]
It may be better to put it in CI of rustdesk drectly.

**Comment by basilgello** [comment]
Pushed this PR and deleted the basilgello/cmake repo

**Comment by rustdesk** [comment]
Great job

**Comment by basilgello** [comment]
Meh…  Looks like CMake buildstep was OOM-killed or something like that: https://github.com/rustdesk/rustdesk/actions/runs/10121883025/job/27993729605

**Comment by basilgello** [comment]
@rustdesk how much cpus/memory do these arm64 runners have? Gonna limit cmake makestep to `-j2` to see if it helps

**Comment by rustdesk** [comment]
4 core / 8G

**Comment by rustdesk** [comment]
let's change to -j1

**Comment by basilgello** [comment]
Done in new PR

**Comment by basilgello** [comment]
Does not help…  Link step silently gets killed. Lets resort to prebuilt cmake as this step id really long and faulty

**Comment by basilgello** [comment]
Found an issue - new PR done

**Pull request merged**
