### PR TITLE
Modernized menu bar

### PR DESCRIPTION
**Pull request by NicKoehler**
after

### CODE REVIEW

**Comment by rustdesk** [comment]
Good looking, but it is not eay to change hover / press any more in the code.

**Comment by NicKoehler** [comment]
You are right, I'll try to fix that

**Comment by rustdesk** [comment]
@NicKoehler could you also modernize our file transfer window? It looks super old school and ugly, including the task list on the right side.

Peek 2023-02-15 15-15

**Comment by rustdesk** [comment]
and port forwad window.

https://github.com/rustdesk/rustdesk/blob/master/flutter/lib/desktop/pages/port_forward_page.dart

image

**Comment by NicKoehler** [comment]
I can try after the menu bar, but now I have an issue that I'm not sure how to fix.. for the last 4 days when I lunch the app with `flutter run ` I receive this error at the top:

```
Launching lib/main.dart on Linux in debug mode...
main.dart:1
[2023-02-15T07:39:33Z INFO  librustdesk::server] DISPLAY=Ok(":1")
[2023-02-15T07:39:33Z INFO  librustdesk::server] XAUTHORITY=Ok("/run/user/1000/gdm/Xauthority")
Connecting to VM Service at ws://127.0.0.1:42043/QIugX25crgw=/ws
flutter: launch args: []
flutter: initializing FFI main
flutter: initialize failed: Invalid argument(s): Failed to lookup symbol 'session_get_rgba': /home/nic/Git-Packages/rustdesk/flutter/build/linux/x64/debug/bundle/lib/librustdesk.so: undefined symbol: session_get_rgba
```

if I launch with `flutter run --release` the error is gone.
It's so slow to build every time with the release flag, I need to fix this..

**Comment by rustdesk** [comment]
Have you run `cargo build --features flutter`?

**Comment by NicKoehler** [comment]
I remembered using it, but evidently not, now it works thank you

**Comment by rustdesk** [comment]
BTW do not forget this button, it will be added when starting audio call.

https://github.com/rustdesk/rustdesk/pull/2981

image

**Comment by NicKoehler** [comment]
Ok, if you could take a look and let me know if there's anything that you think needs to be changed or improved, it would be great

**Comment by rustdesk** [comment]
The mergin of border seems a little small after this new look.

image

**Comment by NicKoehler** [comment]
The margin now is 6 both vertically and horizontally between widgets.

**Comment by rustdesk** [comment]
@NicKoehler the color change below from white to black in black theme seems a little wierd. Do you have any idea?

image

**Comment by NicKoehler** [comment]
Do you mean that half pixel border?

**Comment by rustdesk** [comment]
The border between titlebar and menubar seems invisible.

**Comment by NicKoehler** [comment]
It looks like an optical illusion caused by the fact that the edge is only one pixel wide

image

**Comment by rustdesk** [comment]
true

**Comment by rustdesk** [comment]
Do you think below looks better? or add some decoration on top side of the menu bar.
image

**Comment by NicKoehler** [comment]
Maybe with rounded corners on the top too

**Comment by rustdesk** [comment]
Will try

**Comment by Alintya** [comment]
What about showing the monitors immediately on hover?
That might als satisfy #3333

**Comment by bilago** [comment]
> I did have this idea.

Immediate expanding on hover is a step in the wrong direction imo. The auto expand behavior happens currently in the nightly as I explained in a bug, and causes misclicks on other options.

A suggestion I would make would be:

Show all monitors as individual buttons. Require explicit clicks on menu options.

Add an additional button that you can click on that expands a menu showing the physical location of the connected monitors. This would satisfy the ask of this bug without compromising the new menu bar theme, and retain the feature found in 1.9.x

Pardon my crude mspaint skills:

image

**Comment by rustdesk** [comment]
Auto expand behavior has been removed today.

**Comment by Alintya** [comment]
> > I did have this idea.
> 
> Immediate expanding on hover is a step in the wrong direction imo. The auto expand behavior happens currently in the nightly as I explained in a bug, and causes misclicks on other options.
> 
> A suggestion I would make would be:
> 
> Show all monitors as individual buttons. Require explicit clicks on menu options.
> 
> Add an additional button that you can click on that expands a menu showing the physical location of the connected monitors. This would satisfy the ask of this bug without compromising the new menu bar theme, and retain the feature found in 1.9.x
> 
> Pardon my crude mspaint skills:
> 
> image

i still have the older build and fail to see how that was an actual problem to be honest.
That is like saying we need dedicated buttons to move the remote cursor in either direction because you could mess that up 🙈

**Pull request merged**
