### PR TITLE
vcpkg deps

### PR DESCRIPTION
**Pull request by basilgello**
- macos: Try to patch underlying file and not symlink
- Dont mess CROSS with CC/CXX/etc
- [TEMP] Try disabling LLVM IR bitcode and upload rust target folder to cache
- Ignore CRLF/LF conversion on sciter patch apply
- Do not patch vcpkg - replace the cmake script fully

### CODE REVIEW

**Comment by basilgello** [comment]
Lets try?

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
@basilgello could you look at the failure CI https://github.com/rustdesk/rustdesk/actions/runs/8827504080/job/24234851074?
BTW, can we upgrade vcpkg to some newer version with gcc multiarch support?

**Comment by rustdesk** [comment]
> @basilgello could you look at the failure CI https://github.com/rustdesk/rustdesk/actions/runs/8827504080/job/24234851074? BTW, can we upgrade vcpkg to some newer version with gcc multiarch support?

Please ignore this, I have figured it out.

**Pull request merged**
