### PR TITLE
Dialogs Mobile. Cleanup dialogs with radio/checkbox tiles.

### PR DESCRIPTION
**Pull request by grummbeer**
- Clean up radio/checkbox dialogs
- Adjust style for checkbox/radio tiles

| before | after |
|-- |-- |
|remote-menu-before|remote-menu-after|
|language-before|language-after|
|theme-before|theme-after|
|password-before|password-after-horizonal|

### CODE REVIEW

**Comment by grummbeer** [comment]
the password lenght looks a bit strange, horizontal alignment for options?

**Comment by grummbeer** [comment]
the green shield does not fit to screen/qualtiy settings?

**Comment by rustdesk** [comment]
> the password lenght looks a bit strange, horizontal alignment for options?

yes，ugly

**Comment by rustdesk** [comment]
> the green shield does not fit to screen/qualtiy settings?

looks fine for me

**Comment by grummbeer** [comment]
password-after-horizonal

**Pull request merged**
