### PR TITLE
Fedora build fixes

### PR DESCRIPTION
**Pull request by Nadahar**
I recently built RustDesk on Fedora 39, and came across a couple of issues. These changes "fixes" the issues, but I'm not sure if the fixes are the best/correct fixes, so you should evaluate them before merging.

### `rpm.spec`
- Dependencies `libvdpau1` and `libva2` doesn't exist in Fedora 39 - but `libvdpau` and `libva` do, and everything seems to be working when using them instead. It's strange that they are there if they never existed though, so maybe there are differences between different distros or distro generations? All I know if that they no longer exist in Fedora 39.
- The reference to `__pycache__` failed simply because there were no files there. I don't know if there used to be files there or if I did something wrong, but the RPM package installs and works just fine without this folder.

### `rpath`s
There are some new restrictions in recent versions of `rpmbuild`, among them that all `rpath`s are checked. This prevents building the package, but actually revealed a problem that is true also for others distros. I don't really understand much about CMake, but the "problem" is introduced with the plugin include `include(flutter/generated_plugins.cmake)`.

The way this works is that `rpath`s are set to their current absolute locations at first, and then corrected to their "final" values when the components are "installed". `set(CMAKE_INSTALL_RPATH "$ORIGIN/lib")` is effectuated only during "installation". But, the included "plugins" are never "installed", so their `rpath`s are never corrected. This means that their `rpath`s remain that of their absolute locations when they were build. This path is obviously invalid once they are installed on another computer.

My workaround is to use the "installed" `rpath`s from the start. It will break the ability to run this before the files are packaged, but I'm not sure if that's an issue or not. The correct "fix" would be to call `install` on these "plugins" in some kind of loop in the script, but I don't know how to do that.

### CODE REVIEW

**Comment by rustdesk** [comment]
Apoligize, we do not know, actually, we all build on Ubuntu, then repackage to Fedora.

**Comment by Nadahar** [comment]
Yes, but it still wouldn't hurt if it was possible to build on Fedora as well? Also, the `rpath` problem makes it impossible to install the RPM package on newer Fedora even if it's built on Ubuntu.

**Comment by Nadahar** [comment]
Also, since all the checks (for this PR) passed, I don't think it would break your Ubuntu RPM build.

**Comment by rustdesk** [comment]
Why do you remove /usr/share/rustdesk/files/__pycache__/*?

**Comment by rustdesk** [comment]
We added this `/usr/share/rustdesk/files/pycache/` because we encountered problem before.

**Comment by rustdesk** [comment]
You change to libvdpau1 and libva2, then how about old version?

**Comment by Nadahar** [comment]
> We added this /usr/share/rustdesk/files/pycache/ because we encountered problem before.

The reason I removed it was that it would fail to build the RPM because there were no files in that folder. I don't know the reason for this, if there are supposed to be files there or not - but if there actually are any files there when the RPM is being built, it can stay.

**Comment by Nadahar** [comment]
> You change to libvdpau1 and libva2 for new fedora, then how about old version?

As I said, I don't know the history of this, but it should probably be checked if these packages have changed name. If they have, I don't know if there is a way to "handle both" or not. I think I have a Centos 8 VM I can test on.

**Comment by rustdesk** [comment]
At least, we did not receive report that our rpm can not run on fedora 39.

**Comment by Nadahar** [comment]
I'll test your RPM on Fedora 39 - the `rpath` problem will prevent it from installing as far as I understand, so I don't think it ever comes as far as to having problems with SELinux.

**Comment by Nadahar** [comment]
Regarding `libvdpau1` all I can find when searching for this is a package for Debian/Ubuntu. It looks like it has been named `libvdpau` for a long time in "the Redhat world", this post is from 2011 and applies to Centos 5: https://forums.centos.org/viewtopic.php?t=17236#p82315

**Comment by Nadahar** [comment]
Please note that I've also built RustDesk on OpenSUSE, and on OpenSUSE `libvdpau1` and `libva2` is correct and works. That's why I didn't make any change in `rpm-flutter-suse.spec`. Maybe that's why these are in the "RHEL" `spec` file as well, because one was copied from the other?

**Comment by Nadahar** [comment]
When I try to search for these packages for Fedora, all I get is:
[Did you mean libvdpau?](https://packages.fedoraproject.org/search?query=libvdpau1)
[Did you mean libva? ](https://packages.fedoraproject.org/search?query=libva2)

**Comment by rustdesk** [comment]
It is reopened, but I can not verify it yet, since I have no fedora yet. I will verify when official Fedora 40 is out.

**Comment by Nadahar** [comment]
Yes - I'm still working on testing the current RPM on Fedora 39.

**Comment by rustdesk** [comment]
> > We added this /usr/share/rustdesk/files/pycache/ because we encountered problem before.
> 
> The reason I removed it was that it would fail to build the RPM because there were no files in that folder. I don't know the reason for this, if there are supposed to be files there or not - but if there actually are any files there when the RPM is being built, it can stay.

Any way still keep this but not fail in your build?

**Comment by Nadahar** [comment]
> Any way still keep this but not fail in your build?

I will have to look into it further and see if I can figure it out.

**Comment by Nadahar** [comment]
You are correct that the Ubuntu built RPM works on Fedora 39, so the "new check" is probably just in `rpmbuild` and not used when installing packages. However, after installing it and checking the `rpath` of the installed files, they are wrong as expected:
```bash
# /usr/lib/rustdesk/lib/chrpath libdesktop_drop_plugin.so
libdesktop_drop_plugin.so: RUNPATH=/workspace/flutter/linux/flutter/ephemeral
```
It's the same for all the "plugins". Obviously, `/workspace/flutter/linux/flutter/ephemeral` isn't a valid path.

**Comment by Nadahar** [comment]
Regarding the dependencies, there is something strange going on. Somewhere along the way, something must have "translated" the dependencies or something.

Here is the dependencies output from the RPM I downloaded:
<details>
  <summary>rpm -qpR rustdesk-1.2.3-2.x86_64.rpm</summary>

```bash
/bin/sh
/bin/sh
/bin/sh
/bin/sh
alsa-lib
gstreamer1-plugins-base
gtk3
libXfixes
libappindicator-gtk3
libatk-1.0.so.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libcairo-gobject.so.2()(64bit)
libcairo.so.2()(64bit)
libdesktop_drop_plugin.so()(64bit)
libdesktop_multi_window_plugin.so()(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libflutter_custom_cursor_plugin.so()(64bit)
libflutter_linux_gtk.so()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgdk-3.so.0()(64bit)
libgdk_pixbuf-2.0.so.0()(64bit)
libgio-2.0.so.0()(64bit)
libglib-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libgtk-3.so.0()(64bit)
libm.so.6()(64bit)
libpango-1.0.so.0()(64bit)
libpangocairo-1.0.so.0()(64bit)
libscreen_retriever_plugin.so()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libtexture_rgba_renderer_plugin.so()(64bit)
liburl_launcher_linux_plugin.so()(64bit)
libva
libvdpau
libwindow_manager_plugin.so()(64bit)
libwindow_size_plugin.so()(64bit)
libxcb
libxdo
pam
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rtld(GNU_HASH)
```
</details>

Here is the dependencies output from the RPM I built on Fedora 39:
<details>
  <summary>rpm -qpR rustdesk-1.2.4-rhel.rpm</summary>

```bash
/bin/sh
/bin/sh
/bin/sh
/bin/sh
alsa-lib
gstreamer1-plugins-base
gtk3
ld-linux-x86-64.so.2()(64bit)
ld-linux-x86-64.so.2(GLIBC_2.3)(64bit)
libX11.so.6()(64bit)
libXfixes
libXfixes.so.3()(64bit)
libXtst.so.6()(64bit)
libappindicator-gtk3
libatk-1.0.so.0()(64bit)
libc.so.6()(64bit)
libc.so.6(GLIBC_2.10)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libc.so.6(GLIBC_2.15)(64bit)
libc.so.6(GLIBC_2.16)(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libc.so.6(GLIBC_2.18)(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.25)(64bit)
libc.so.6(GLIBC_2.28)(64bit)
libc.so.6(GLIBC_2.29)(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.3)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.32)(64bit)
libc.so.6(GLIBC_2.33)(64bit)
libc.so.6(GLIBC_2.34)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.6)(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libc.so.6(GLIBC_2.8)(64bit)
libc.so.6(GLIBC_2.9)(64bit)
libcairo-gobject.so.2()(64bit)
libcairo.so.2()(64bit)
libdbus-1.so.3()(64bit)
libdbus-1.so.3(LIBDBUS_1_3)(64bit)
libdesktop_drop_plugin.so()(64bit)
libdesktop_multi_window_plugin.so()(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libepoxy.so.0()(64bit)
libfile_selector_linux_plugin.so()(64bit)
libflutter_custom_cursor_plugin.so()(64bit)
libflutter_linux_gtk.so()(64bit)
libfontconfig.so.1()(64bit)
libgcc_s.so.1()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libgcc_s.so.1(GCC_3.3)(64bit)
libgcc_s.so.1(GCC_4.2.0)(64bit)
libgdk-3.so.0()(64bit)
libgdk_pixbuf-2.0.so.0()(64bit)
libgio-2.0.so.0()(64bit)
libglib-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libgstapp-1.0.so.0()(64bit)
libgstreamer-1.0.so.0()(64bit)
libgstvideo-1.0.so.0()(64bit)
libgtk-3.so.0()(64bit)
libharfbuzz.so.0()(64bit)
libm.so.6()(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libm.so.6(GLIBC_2.27)(64bit)
libm.so.6(GLIBC_2.29)(64bit)
libm.so.6(GLIBC_2.35)(64bit)
libm.so.6(GLIBC_2.38)(64bit)
libpango-1.0.so.0()(64bit)
libpangocairo-1.0.so.0()(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libpthread.so.0(GLIBC_2.3.3)(64bit)
libpulse-simple.so.0()(64bit)
libpulse-simple.so.0(PULSE_0)(64bit)
libpulse.so.0()(64bit)
libpulse.so.0(PULSE_0)(64bit)
libscreen_retriever_plugin.so()(64bit)
libstdc++.so.6()(64bit)
libstdc++.so.6(CXXABI_1.3)(64bit)
libstdc++.so.6(CXXABI_1.3.5)(64bit)
libstdc++.so.6(GLIBCXX_3.4)(64bit)
libstdc++.so.6(GLIBCXX_3.4.11)(64bit)
libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
libstdc++.so.6(GLIBCXX_3.4.29)(64bit)
libstdc++.so.6(GLIBCXX_3.4.32)(64bit)
libstdc++.so.6(GLIBCXX_3.4.9)(64bit)
libtexture_rgba_renderer_plugin.so()(64bit)
liburl_launcher_linux_plugin.so()(64bit)
libva
libva-drm.so.2()(64bit)
libva-x11.so.2()(64bit)
libva.so.2()(64bit)
libva.so.2(VA_API_0.33.0)(64bit)
libvdpau
libvdpau.so.1()(64bit)
libwindow_manager_plugin.so()(64bit)
libwindow_size_plugin.so()(64bit)
libxcb
libxcb-randr.so.0()(64bit)
libxcb-shm.so.0()(64bit)
libxcb.so.1()(64bit)
libxdo
libxdo.so.3()(64bit)
libxkbcommon.so.0()(64bit)
libxkbcommon.so.0(V_0.5.0)(64bit)
libz.so.1()(64bit)
pam
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rtld(GNU_HASH)
```
</details>

Except for the weird `GLIBC` lines, they seem to be pretty similar.

**Comment by Nadahar** [comment]
Now I understand 💡 

I've changed `rpm.spec` - not `rpm-flutter.spec`. In `rpm-flutter.spec` these are already correctly specified. That probably explains why there has been no reported problems, this `.spec` file only applies to the Sciter version, and I'm guessing that you don't automatically build that anymore? The dependencies were introduced in d465792d419f5d6a7bb542602b08fc9578c514eb - and you were probably using Flutter as standard already then? This also explains why the dependencies are "correct" in the RPM I downloaded - that's the Flutter version as well - and it has the correct dependencies.

**Comment by Nadahar** [comment]
Regarding `__pycache__`, you don't have this in any of the other `.spec` files either - only in the "Sciter RPM for RHEL/Fedora", and it seems to me like it was never added but was in this file from the start: 222245a60c36f885fd7077374077cfaf01077a4a

**Comment by rustdesk** [comment]
i have no interest to spend time on such things, sorry.

**Pull request closed without merging**
