### PR TITLE
fix key stick

### PR DESCRIPTION
**Pull request by fufesou**
Signed-off-by: fufesou <shuanglongchen@yeah.net>

### CODE REVIEW

**Comment by rustdesk** [comment]
CI failed

**Comment by rustdesk** [comment]
confliction

**Comment by rustdesk** [comment]
Seems something wrong, asur4s's commit already merged before, you submit here again.

**Comment by fufesou** [comment]
I did `git rebase master` locally.

**Comment by rustdesk** [comment]
rebase is dangerous.

**Pull request closed without merging**
