### PR TITLE
fix key check in nightly yaml

### PR DESCRIPTION
**Pull request by botanicvelious**
Looks like the yaml got overwritten so it broke when there was no keys

### CODE REVIEW

**Comment by rustdesk** [comment]
I do this intentionaly, because your env.MACOS_P12_BASE64 is not defined, and its value is not 'true"also.

**Comment by rustdesk** [comment]
Without MACOS_P12_BASE64 etc, does not affect generating final files.

**Comment by botanicvelious** [comment]
> Without MACOS_P12_BASE64 etc, does not affect generating unsigned final files.

It actually does, for example on my github actions you can see it fails without this https://github.com/botanicvelious/rustdesk/actions/runs/3946886853 If you look at the osx build you can see it fails with "Error: At least one of p12-filepath or p12-file-base64 must be provided"

but with it there is a success https://github.com/botanicvelious/rustdesk/actions/runs/3947551708

>I do this intentionaly, because your env.MACOS_P12_BASE64 is not defined, and its value is a string rather than "true".

The check is checking to see if it exists not checking the value of it

**Comment by rustdesk** [comment]
where is it defined?

**Comment by botanicvelious** [comment]
Ah I see your confusion, secrets.MACOS_P12_BASE64 maps to env.MACOS_P12_BASE64 automatically, ill clear up the pr so its consistant

**Comment by rustdesk** [comment]
If I set `secrets.MACOS_P12_BASE64` to `"abcd"`, `${{ env.MACOS_P12_BASE64== 'true' }}` also works?

**Comment by botanicvelious** [comment]
So I found the issue and fixed it, if you can re-open this pr so i can update it 👍

**Comment by botanicvelious** [comment]
Basically there are 2 issues, first the "if" only allows env. values not secrets. values so i have to set the env. value to the secret value, then the second problem was my syntax was borked, it should be if: env.MACOS_P12_BASE64 != null

**Comment by botanicvelious** [comment]
Looks like it synced, everything should work properly now when merged.

**Pull request merged**
