### PR TITLE
remove flutter extra "waiting for image"

### PR DESCRIPTION
**Pull request by 21pages**

### CODE REVIEW

**Comment by rustdesk** [comment]
Have you tested reconnect?

**Comment by 21pages** [comment]
no

**Comment by 21pages** [comment]
just tested, it's ok

**Comment by rustdesk** [comment]
reconnect has "wait for image" dialog?

**Comment by 21pages** [comment]
Yes, it seems that remote will receive peerinfo again.

**Comment by rustdesk** [comment]
If so, wait_for_first_image seems useless.

**Comment by 21pages** [comment]
waiting_for_imaged ialog may show after the first image, that's why I split it.

**Pull request merged**
