### PR TITLE
Update cn.rs

### PR DESCRIPTION
**Pull request by Integral-Tech**

### CODE REVIEW

**Comment by rustdesk** [comment]
Could you please modify below only? 

        ("Change view", "更改视图"),
        ("Big tiles", "大磁贴"),
        ("Small tiles", "小磁贴"),
        ("List", "列表"),

**Comment by Integral-Tech** [comment]
> Could you please modify below only?
> 
> ```
>     ("Change view", "更改视图"),
>     ("Big tiles", "大磁贴"),
>     ("Small tiles", "小磁贴"),
>     ("List", "列表"),
> ```

Some other translations does not follow the language habit of Simplified Chinese :(

**Comment by rustdesk** [comment]
> Some other translations does not follow the language habit of Simplified Chinese :(

Those comes from native Chinese actually.

**Comment by Integral-Tech** [comment]
Okay, I have modified the commit

**Pull request merged**
