### PR TITLE
Enlarge window title bar

### PR DESCRIPTION
**Pull request by grummbeer**
Enlarged title bar is in good company, looks modern and - most important - the tabs are much easier to hit.

titlebar-enlarged

### CODE REVIEW

**Comment by grummbeer** [comment]
> Branding

As it came up in the UX/UI discussion, there is this nice "RustDesk" next to the logo in titlebar, why not show it for the main window?

anyway, what is the correct visual representation? "RustDesk" or "rustdesk" or "RUSTDESK"?

**Comment by rustdesk** [comment]
RustDesk

**Comment by grummbeer** [comment]
> RustDesk. I thought logo is enough

OK.

> But personally, I do not like big title bar.

OK.

For me, the very small tabs are difficult to hit. 

Although the mouse pointer is very precise, it seems to be somehow intelligent and reflect my thick fingers 1:1, so that i often need more tries to hit them.

**Comment by grummbeer** [comment]
> "RustDesk"

Change the header image in the README accordingly?

**Comment by grummbeer** [comment]
> larger title bar 

Sorry for bothering, but i am on fire. Since this is a personally (ignoring UX) thing, would it OK for you to make this configurable? Settings > Titlebar "small", "medium", "large" or a individual value?

**Comment by rustdesk** [comment]
> ould it OK for you to make this configurable? Settings > Titlebar "small", "medium", "large" or a individual value?

Totally agree if you do not modify the default one.

**Comment by grummbeer** [comment]
> Totally agree if you do not modify the default one.

nope, your are the benchmark!

**Comment by grummbeer** [comment]
> Branding

Do you prefer a specific font for your brand? Which one have you used for the readme header?

> title bar

preview, but have issues on opening another window. I may discard the idea for now :-(
enlarged-title-bar

**Comment by rustdesk** [comment]
> preview, but have issues on opening another window. I may discard the idea for now :-(

A dialog is better for this.

**Comment by grummbeer** [comment]
> I use all lower case in the logo because it seems more pretty.

Yeah, i agree. All occurrences are harmonized to "rustdesk" with the font you used on the website? Means no more "RustDesk", right?

**Comment by rustdesk** [comment]
I use "RustDesk" when there is no logo.

**Comment by grummbeer** [comment]
first try, clean and floating above all

https://github.com/grummbeer/rustdesk/tree/readme-brand

Change switching your github theme preferencies dark/light mode

**Pull request closed without merging**
