### PR TITLE
Created "simple" da Lang file

### PR DESCRIPTION
**Pull request by ghost**
Added a simple language file "da.rs" so the UI can show the Danish language 🇩🇰

(Google Translate is used)
Feel free to correct it.

### CODE REVIEW

**Comment by mikkolukas** [comment]
The translations in Danish are quite wrong.

Seems to be a fast google translate job.

**Comment by rustdesk** [comment]
Yes, will be in next release.

**Comment by Ylacat** [comment]
@mikkolukas I added the file so at least a Danish lang file existed. I'm sorry if it has caused you pain.

**Comment by Ylacat** [comment]
@mikkolukas Yes. I was gonna do a spellcheck when the language option come out. As well as publish the doc and ReadMe. 

But feel free to correct it and add the rest.

**Comment by rustdesk** [comment]
@Ylacat before the language option on GUI comes out, you can also modify it via config file, https://github.com/rustdesk/rustdesk/issues/709#issuecomment-1159690164

**Pull request merged**
