### PR TITLE
android: for software encoding and screen size > 1200, display size reduced to half

### PR DESCRIPTION
**Pull request by 21pages**
https://github.com/rustdesk/rustdesk/pull/8002

It's for encoding speed, and mouse is still ok.

https://github.com/rustdesk/rustdesk/assets/14891774/106596bd-6802-432d-9f3e-61509a6d59a6

### CODE REVIEW

**Comment by haisong66** [comment]
What should I do if there is no hardware encoding and I don’t want the display to be too small?

https://github.com/rustdesk/rustdesk/assets/168391999/8486652f-e3ae-4f7d-a688-7e4a073a5492

**Comment by haisong66** [comment]
Can it be adjusted to >1920 or 1600 to reduce the display size by half? Otherwise the 1366 tablet display is too small.

**Comment by haisong66** [comment]
> Can it be adjusted to >1920 or 1600 to reduce the display size by half? Otherwise the 1366 tablet display is too small.

@rustdesk @21pages

**Comment by rustdesk** [comment]
@haisong66 No answering, means no. Stop bothering.

**Comment by rustdesk** [comment]
Full size is available if no hardware codec for custom client build, https://rustdesk.com/docs/en/self-host/client-configuration/advanced-settings/#andriod-software-encoding-half-scale

**Pull request merged**
