### PR TITLE
Improved fix for connection refused on restart/logout lightdm

### LINKED ISSUE #5126: After restarting the Linux system: connection refused (Debian12 xfce)
### Bug Description

After restarting the system. stay on the login screen.

then remote control through RustDesk.

rustdesk: connection refused

log in via ssh, check the log

sudo journalctl -f
```
7月 26 17:09:59  rustdesk[2851]: No protocol specified
7月 26 17:09:59  rustdesk[2851]: No protocol specified
7月 26 17:10:01  systemd[1]: todeskd.service: Scheduled restart job, restart counter is at 366.
7月 26 17:10:01  systemd[1]: Stopped todeskd.service - ToDesk Daemon Service.
7月 26 17:10:02  systemd[1]: Started todeskd.service - ToDesk Daemon Service.
7月 26 17:10:02  kernel: traps: ToDesk_Service[25962] trap invalid opcode ip:4d06da sp:7ffd9c3c96a0 error:0 in ToDesk_Service[400000+140f000]
7月 26 17:10:02  systemd[1]: todeskd.service: Main process exited, code=killed, status=4/ILL
7月 26 17:10:02  systemd[1]: todeskd.service: Failed with result 'signal'.
7月 26 17:10:03  sudo[26003]:  user1 : TTY=pts/1 ; PWD=/home/user1 ; USER=root ; COMMAND=/usr/bin/journalctl -f
```

### How to Reproduce

After restarting the system. stay on the login screen.

then remote control through RustDesk.

It is normal after logging in to Linux.

### Expected Behavior
-

### Operating system(s) on local side and remote side

Debian12 xfce

### RustDesk Version(s) on local side and remote side

1.2.1

### Screenshots

image

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by beelchester**
This PR fixes #5126, and reduces the offline time as faced in #5248 

`Login error: Connection refused` was caused due to wrong seat0 active user value. It occurred once in a while on restarting and occasionally upon logging out. It was because lightdm takes some time for user switching, whereas in my experience gdm was faster and better.

My previous PR #5212 resolved this problem not through multiple attempts but by introducing a delay, allowing lightdm to produce the correct seat0 active user value. I removed the code from #5212 as it offered no advantage since empty seat0 values were already handled.

The changes in this PR are discussed below.

**Before**

https://github.com/rustdesk/rustdesk/assets/73148455/243b1c69-a9ce-4479-bc51-d24aa7304536

Like I said #5212 solved this issue but wasn't the best solution.

**Now**  (This PR)

https://github.com/rustdesk/rustdesk/assets/73148455/6cb80081-af47-4f59-8a5b-f9c20c7d0921

### CODE REVIEW

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/discussions/5095

**Comment by sahilyeole** [comment]
> This may fix lightgdm, but it does not fix `Login error: Connection refused` without lightgdm.

I was not able to reproduce `Login error: Connection refused` for gdm in nightly build. But I will check more.

**Comment by rustdesk** [comment]
We need a universal solution, rather than handle lightgdm specifically in this way.

**Comment by sahilyeole** [comment]
I think https://github.com/rustdesk/rustdesk/pull/5276/commits/897dc1c2ba7ca2c03b6d6d11cbc92de624a76bf4 should be the universal solution for `Login error: Connection refused`

https://github.com/rustdesk/rustdesk/pull/5276/commits/d28d3baf056f09509fcc0813295ac6024e762806 was for reducing time for refresh on lightdm login screen but I should have checked for other display managers too. I'm working on it

**Comment by rustdesk** [comment]
Can not accept a fix like https://github.com/rustdesk/rustdesk/commit/897dc1c2ba7ca2c03b6d6d11cbc92de624a76bf4, not like a serious coding, though it works for you.

**Comment by sahilyeole** [comment]
Yes, understandable.
I'll work more for finding a better solution.

**Comment by sahilyeole** [comment]
How about this instead of https://github.com/rustdesk/rustdesk/commit/897dc1c2ba7ca2c03b6d6d11cbc92de624a76bf4 for `Login error: Connection refused`?

I've noticed there could be multiple active sessions (if suppose someone is connected through ssh too), so we can't solely rely on `is_active()`.
Here I have added an extra check to ensure the session is seat0 then skip refresh else refresh to get the latest seat0 values.
I have tested it, this works as expected.

It works irrespective of display managers and their capabilities.

```rust
pub fn refresh(&mut self) {
            let seat0_values = get_values_of_seat0(&[0, 1, 2]);
            if !self.sid.is_empty() && is_active(&self.sid) {
                   if self.sid == seat0_values[0] {  // check
                        return;
                    }
            }
            //......
```

**Comment by rustdesk** [comment]
Let's try

**Comment by sahilyeole** [comment]
Ok sure, I have tested it with Debian XFCE and gnome. I will test for a few other distros and DEs too.

**Comment by sahilyeole** [comment]
Also, should I remove https://github.com/rustdesk/rustdesk/pull/5276/commits/d28d3baf056f09509fcc0813295ac6024e762806, it is very lightdm specific.

**Comment by rustdesk** [comment]
Remove

**Comment by rustdesk** [comment]
How about the testing?

**Comment by sahilyeole** [comment]
Still testing. I will update you very soon.

**Comment by sahilyeole** [comment]
Tested: debian xfce (lightdm), manjaro gnome (arch, x11, gdm), ubuntu (x11, gdm), kubuntu kde(sddm).

Can confirm this fix is ensuring the correct seat0 active user and `Login error: Connection refused` did not occur on restart/login.

**Comment by rustdesk** [comment]
> back to 10 from 20,

I will do

**Pull request merged**
