### PR TITLE
Feat connect to peer on another server

### PR DESCRIPTION
**Pull request by beelchester**
**Still working**

https://github.com/rustdesk/rustdesk/issues/6198#issuecomment-1782696098
Currently, I'm able to connect a peer on the public server while the control side is connected to a private server.
Support for public -> private in progress.

Ex: 143242314@164.432.413: 21116?key=32432432Efdsf34 or 143242314@public

https://github.com/rustdesk/rustdesk/assets/73148455/82ee7e63-147a-4e98-aa18-2f993d20fc06

### CODE REVIEW

**Comment by sahilyeole** [comment]
@rustdesk How can I know which public server the peer is connected to?
Currently, I have hardcoded it just for testing.
Or else I can loop and try every public server we have when user provides `@public`.

---
Also with this implementation, I'm getting the unencrypted connection. How can I encrypt it?

Screenshot_20231028_053044

**Comment by rustdesk** [comment]
that is you need to figure out

**Comment by rustdesk** [comment]
> public

You need to take care of this case https://rustdesk.com/docs/en/self-host/client-configuration/hardcode-settings/

**Comment by rustdesk** [comment]
No need to take care of multiple public servers, just use the first one, in the future we will use only one.

**Comment by sahilyeole** [comment]
> No need to take care of multiple public servers, just use the first one, in the future we will use only one.

Ok so I'm currently using `rs-ny.rustdesk.com:21116` server for `@public`. Is that enough?

**Comment by sahilyeole** [comment]
I have added support to get the private server key from the text field but I'm getting this error on connecting:

Screenshot 2023-10-29 at 5 15 03 AM

as connection to private servers requires login credentials of the user allowed on that server.

So I can try this text field expression:
Ex: `143242314@164.432.413:21116?key="32432432Efdsf34"?username="admin"?password="admin1234"`
and authenticate the user for that server only for this particular connection.

Also, according to this, I think adding user credentials for the text field expression might be good. https://github.com/rustdesk/rustdesk/issues/6198#issuecomment-1782808127
>We'd need to find a way of making it impossible to copy the key, or of making this possible only if the Rustdesk user is logged in. Otherwise, the key could spread and my server become public...

Should we try this?

**Comment by rustdesk** [comment]
> > No need to take care of multiple public servers, just use the first one, in the future we will use only one.
> 
> Ok so I'm currently using `rs-ny.rustdesk.com:21116` server for `@public`. Is that enough?

Can not be hard coded, it may change in the future.

**Comment by rustdesk** [comment]
> Should we try this?

No

**Comment by rustdesk** [comment]
> as connection to private servers requires login credentials of the user allowed on that server.

Expected, no need to consider for now.

**Comment by rustdesk** [comment]
Also make sure `143242314@164.432.413: 21116?key=32432432Efdsf34` works for uri, e.g. `rustdesk://143242314@164.432.413: 21116?key=32432432Efdsf34`.

**Comment by sahilyeole** [comment]
- Used RENDEZVOUS_SERVERS to get public server
- URL connection done on macos. Windows & linux yet to check
- Private -> public still working on the encryption part

**Comment by rustdesk** [comment]
I will take over this issue.

**Pull request closed without merging**
