### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by Mr-Update**

### CODE REVIEW

**Comment by grummbeer** [comment]
please fix encoding
```
("Resolution", "AuflÃ¶sung"),
("No transfers in progress", "Keine Ãœbertragungen im Gange"),
```

**Comment by Mr-Update** [comment]
@grummbeer The encoding in the 'Commits' tab is OK.

The encoding in the 'Files changed' tab is wrong only for README-DE.md and de.rs.
After clicking on 'Display the rich diff' at the file README-DE.md the encoding is correct and suddenly after clicking on 'Display the source diff' also there!
After clicking on 'View file' at the file de.rs the encoding is also correct!

In the branch 'patch-1' in my fork all 4 files are ok.

In summary: I am at a loss.

**Comment by grummbeer** [comment]
your right, no idea whats going wrong with the "Files changed" view.

**Comment by rustdesk** [comment]
Interesting.

**Comment by rustdesk** [comment]
Github Bug

**Comment by grummbeer** [comment]
@Mr-Update I want to learn more about the translations, would be nice if you can help me.

can you have a look to https://github.com/rustdesk/rustdesk/pull/3431


### Context

what do you think is the reason for this missmatch

- wrong button text
- "aktivieren" aber unten steht "öffen/schließen"

mobile-context-page-settings

in the translation file "de.rs", the parts are far from each other.

```
Line 12  ("Start Service", "Vermittlungsdienst starten"),
                            ^^^^^^^^^^ [1] ^^^^^^^^^^^

Line 273 ("CLOSE", "SCHLIEẞEN"),
Line 274 ("OPEN", "ÖFFNEN"),    
                   ^[2]^^^                       
Line 293 ("android_start_service_tip", "Tippen Sie auf \"Dienst aktivieren\" oder aktivieren Sie die Berechtigung \"Bildschirmaufnahme\", um den Bildschirmfreigabedienst zu starten."),
                                                         ^^^^^^ [1] ^^^^^^^      ^^^ [2] ^^^

```

- How do you keep care of the context?
- Could it help grouping translatables more together?
- What do you think of placeholders "Tippen Sie auf "`%button.start_start.text%`" oder …"
- Do you have an idea of what would be necessary for you to produce better quality and more contextual translations?

Danke!

**Comment by grummbeer** [comment]
> What do you think of placeholders "Tippen Sie auf "%button.start_service.text%" oder …"

and in translation file somthing like that

```
("mobile.settings.service.button.start_service.text", "Vermittlungsdienst starten")
("mobile.settings.service.disabled_service.description", 
     "Tippen Sie auf \"%mobile.settings.service.button.start_service.text%\" oder
      aktivieren Sie die Berechtigung \"Bildschirmaufnahme\", um den Bildschirmfreigabedienst
      zu starten."),
```

**Comment by Mr-Update** [comment]
@ grummbeer
> * How do you keep care of the context?
> * Do you have problems with figuring out which text is placed where in the UI?
> * Could it help grouping translatables more together?
> * What do you think of placeholders "Tippen Sie auf "`%button.start_service.text%`" oder …"
> * Do you have an idea of what would be necessary for you to produce better quality and more contextual translations?

A wonderful idea to see where the text is placed is the tool TrlUtil for Keepass (https://keepass.info/translations_devinfo.html).
In the 'Dialogs' tab, clicking on an entry shows the translated text in an extra window (behind it). This opens up the context and the text length can be judged well.

Placeholders are a very good idea for consistent translation.

For the explanation of the context a comment in Template.rs would be helpful, e.g. at "Elevate".

**Comment by grummbeer** [comment]
Danke! Schönen Abend noch.

**Pull request merged**
