### PR TITLE
Fix icon name in .desktop entry to allow theming

### PR DESCRIPTION
**Pull request by SelfRef**
Current icon path doesn't allow to replace used icon with the one from currently applied icon theme in the system. By using symbolic name instead of absolute path the icon is determined using lookup mechanism described in [XDG Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup).

### CODE REVIEW

**Comment by rustdesk** [comment]
`/usr/share/rustdesk/files/rustdesk.png` can be found automatically and magically?

**Comment by SelfRef** [comment]
> can `/usr/share/rustdesk/files/rustdesk.png` be found automatically and magically?

The correct path for icon is `/usr/share/icons/hicolor/256x256/apps/rustdesk.png`. If the icon is placed in this directory then it will be used only by name. Every distro package should place it there because it's in the [XDG specs](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons).

E.g. Arch package [does that correctly](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rustdesk-nightly).

**Comment by rustdesk** [comment]
So you need modify more things.

**Comment by rustdesk** [comment]
image

**Comment by rustdesk** [comment]
And test different distors, at least ubuntu, fedora, arch.

**Comment by SelfRef** [comment]
I see, there are included build scripts in this repo. OK, I will modify them and test on different distros today.

**Comment by SelfRef** [comment]
OK, bundling all packages took me a while but I've tested them (all compiled natively using `build.py`) after changing build scripts. Additionally I extracted SVG version of the icon from `design.svg` and added it to icons as well. Nowadays Gnome and KDE use primarily SVGs and treat PNGs as fallback.

Where | Screenshot
--- | ---
Arch, XFCE, Whisker & Applications menu | image image
Arch, Gnome | image
Arch, KDE Plasma | image
Ubuntu 22.04 LTS, Gnome | image
Fedora Workstation 38, Gnome | image

**Comment by rustdesk** [comment]
Looks very good. Have you tested packages (including AppImage and flatpak)  generated by CI?

**Comment by rustdesk** [comment]
on your fork

**Comment by rustdesk** [comment]
@SelfRef do you have any update?

**Comment by SelfRef** [comment]
> @SelfRef do you have any update?

Sorry, I forgot to mention I was going on vacation.

I [ran CI](https://github.com/SelfRef/rustdesk/releases/tag/nightly) and checked both Flatpak and AppImage. In case of Flatpak the change is working as intended - icon is visible and can be themed. AppImage works as before, I don't think they can be themed so that's fine.

Where | Screenshot
--- | ---
Arch, Gnome, Flatpak | Screenshot from 2023-08-13 23-45-04 image
Arch, Gnome with [icon theme](https://github.com/vinceliuice/Tela-icon-theme), Flatpak | Screenshot from 2023-08-13 23-51-30 Screenshot from 2023-08-13 23-51-52
Arch, Gnome, AppImage | Screenshot from 2023-08-13 23-54-55
Arch, Xfce, Flatpak | Screenshot from 2023-08-14 00-10-59
Arch, Xfce, AppImage | Screenshot from 2023-08-14 00-12-55

**Comment by rustdesk** [comment]
good job

**Pull request merged**
