### PR TITLE
vcpkg deps

### PR DESCRIPTION
**Pull request by basilgello**

### CODE REVIEW

**Comment by basilgello** [comment]
@rustdesk @21pages

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/actions/runs/10015711942/job/27687554916

https://github.com/21pages/rustdesk/releases/download/nightly/install-x64-linux-dbg-out.log

` fatal: unable to open include file `third_party/x86inc/x86inc.asm'`

**Comment by basilgello** [comment]
What's happened with https://github.com/fufesou ? Page not found, repos like The-Fat-Controller are unavailable.

**Comment by basilgello** [comment]
So far to build vcpkg inside ubuntu18.04:

* update of nasm to 2.16 from `ppa:savoury1/backports` does resolve missing include but fails later on; disabling assembly for aom makes it build even with nasm from ubuntu
* meson needs newer python, install `python3.7` from `ppa:savoury1/python` and make it python3: `update-alternatives /usr/bin/python3 python3 /usr/bin/python3.7 1`
* until fufesou is unblocked, builds fail

**Comment by 21pages** [comment]
Only ffmpeg build in docker is another choice.

**Comment by basilgello** [comment]
FFmpeg builds fine inside 18.04 - I have just tested. It is https://github.com/fufesou/rdev, https://github.com/fufesou/The-Fat-Controller, https://github.com/fufesou/mouce missing due to https://github.com/fufesou missing

**Comment by basilgello** [comment]
fcntl64 on 18.04 used by sciter builds is disabled

**Comment by basilgello** [comment]
@rustdesk renamed or blocked github account of fufesou will break every builds after github action cache expires. Please try to restore all needed repos under rustdesk-org

**Comment by basilgello** [comment]
From cargo.lock:

```
Cargo.lock:source = "git+https://github.com/fufesou/evdev#cec616e37790293d2cd2aa54a96601ed6b1b35a9"
Cargo.lock:source = "git+https://github.com/fufesou/mouce.git#ed83800d532b95d70e39915314f6052aa433e9b9"
Cargo.lock:source = "git+https://github.com/fufesou/pam#3a2aaa6e07b176d8e2d66a5eec38d2ddb45f009f"
Cargo.lock:source = "git+https://github.com/fufesou/pam-sys?branch=fix/v1.0.0-alpha4_gnuc_va_list#3337c9bb9a9c68d7497ec8c93cad2368c26091b7"
Cargo.lock:source = "git+https://github.com/fufesou/rdev#b3434caee84c92412b45a2f655a15ac5dad33488"
Cargo.lock:source = "git+https://github.com/fufesou/The-Fat-Controller#9dd86151525fd010dc93f6bc9b6aedd1a75cc342"
```

**Comment by basilgello** [comment]
Lin told me by email thst Github has flagged his account

**Comment by rustdesk** [comment]
> blocked github account of fufesou

?

**Comment by basilgello** [comment]
I asked fufesou by email why all his repos report 404 Not Found and he replied he woke up and seen Github flagged his account

**Comment by deep-soft** [comment]
If account is just flagged, but not blocked, he can pull all the repos, locally, before the account will be locked/blocked.
My account was flagged and, one day after, blocked. It took me three months to get back access to my account.

**Comment by rustdesk** [comment]
@fufesou let us transfer all repos to rustdesk-org

**Comment by rustdesk** [comment]
@basilgello why did github flag / block you?

**Comment by basilgello** [comment]
@rustdesk Not me :) it is linlong's aka fufesou whose account is flagged

**Comment by basilgello** [comment]
I made sure vcpkg step completes on bionic docker image for sciter build - now I have to wait until the crates become available back.

**Comment by deep-soft** [comment]
@basilgello 
Compilation for Windows, warning:
Use MSVC to compile libyuv results in a very slow library. 
(https://github.com/microsoft/vcpkg/issues/28446)

I tried to add patches for vcpkg/ports/libyuv
from here:
https://github.com/dchapyshev/vcpkg4aspia/tree/master/ports/libyuv/
but on compilation of libyuv there is an error about an invalid patch
[fix-cmakelists.patch](https://github.com/dchapyshev/vcpkg4aspia/blob/master/ports/libyuv/fix-cmakelists.patch)

**Comment by basilgello** [comment]
@deep-soft Thanks for the hint! I will look at the patchset after I sort nasm thingy for sciter

**Comment by basilgello** [comment]
@deep-soft added

**Comment by deep-soft** [comment]
> @deep-soft added

Thank you!

But same error I encounter:
Error:   Applying patch failed: error: corrupt patch at line 14

Something is wrong in "fix-cmakelists.patch"

Today I was trying the other way:
1. removed res/vkpkg/libyuv folder
2. changed only portfile.cmake, directly in C:\vcpkg\ports\libyuv\portfile.cmake
3. but CI was failing because fufesou account was flagged
4. I'll wait for changes regarding fufesou repos and I'll try again.

**Comment by deep-soft** [comment]
Changes regarding fufesou repos already applied.
I managed to build (Windows portion), successfully, with libyuv patch applied.
Don't know why if I put the files in res/vcpkg/libyuv error: Error: Applying patch failed: error: corrupt patch at line 14
If I create one zip archive with same files and unpack it in the res/vcpkg/libyuv folder (after checkout, before other actions) the patch is successfully and the yuv.lib is compiled with clang-cl.exe instead of cl.exe (as in https://github.com/microsoft/vcpkg/issues/28446).
The warning appears in the logs but the yuv.lib is different, I checked files in vcpkg_installed folder and in C:\vcpkg.

**Comment by basilgello** [comment]
@deep-soft might be related to CRLF processing

**Comment by basilgello** [comment]
Rewriting the patch to leave first 3 lines intact solves the failure but build failures occur due to https://github.com/microsoft/vcpkg/issues/37968

**Comment by deep-soft** [comment]
[libyuv-patch.zip](https://github.com/user-attachments/files/16323087/libyuv-patch.zip)

I've added the files from libyuv patch.

How I used?!
1. res/vcpkg/libyuv does not exist
2. add to flutter-build.yml, after
      - name: Checkout source code
        uses: actions/checkout@v4
these:
      - name: patch vcpkg/libyuv (from bins/zip)
        continue-on-error: true
        shell: cmd
        run: |
          7z.exe x -ores/vcpkg/libyuv/ bins/libyuv-patch.zip
          dir res\vcpkg
          dir res\vcpkg\libyuv

If I try to put those files directly in res/vcpkg/libyuv folder the error appears, otherwise compilation is successfull.
I didn't tested yet the for the other OS (linux, android ...)

**Comment by basilgello** [comment]
> [libyuv-patch.zip](https://github.com/user-attachments/files/16323087/libyuv-patch.zip)
> 
> I've added the files from libyuv patch.
> 
> How I used?!
> 
> 1. res/vcpkg/libyuv does not exist
> 2. add to flutter-build.yml, after
>    
>    * name: Checkout source code
>      uses: actions/checkout@v4
>      these:
>    * name: patch vcpkg/libyuv (from bins/zip)
>      continue-on-error: true
>      shell: cmd
>      run: |
>      7z.exe x -ores/vcpkg/libyuv/ bins/libyuv-patch.zip
>      dir res\vcpkg
>      dir res\vcpkg\libyuv
> 
> If I try to put those files directly in res/vcpkg/libyuv folder the error appears, otherwise compilation is successfull. I didn't tested yet the other OS (linux, android ...)

I already applied the patch and re-diffed it with slight modifications so it applies cleanly even on windows.

The build failures you see are from different bug that I will solve later today.

**Comment by deep-soft** [comment]
I seen this (compilation ok on windows).
I've created the zip with files from microsoft/vcpkg/ports/libyuv folder
and replaced only the portfile.cmake from vcpkg4aspia
I used VCPKG_COMMIT_ID: "f7423ee180c4b7f40d43402c2feb3859161ef625"

> 
> I already applied the patch and re-diffed it with slight modifications so it applies cleanly even on windows.
> 
> The build failures you see are from different bug that I will solve later today.

**Comment by rustdesk** [comment]
> very slow

@deep-soft do you see the slowness in our current release?

**Comment by deep-soft** [comment]
After each compilation I check list of warnings; for this warning I tried to find the fix, but failed.
When I see basilgello working on fix for vcpkg I tried with him to fix this warning also.
Maybe the slowness, for powerfull computers, it's not that obvious.
I will try to make some benchmarks, with both versions (with and without the fix).

**Comment by rustdesk** [comment]
Thanks @deep-soft

**Comment by basilgello** [comment]
@deep-soft build of i686-winfows-msvc passes. Need to check sciter build.

**Comment by basilgello** [comment]
@21pages please run sciter builds of the latest commit

**Comment by deep-soft** [comment]
My workflows, because of the three months account lock, it's not updated to last commits.
I managed to update workflows and build successfully for two OS:  windows x64 and linux amd64 (deb).
I also have version before libyuv patch to check to.
But I must find what and how to do the benchmarks to test libyuv patch (if any differences).
Any clue?!

> @deep-soft build of i686-winfows-msvc passes. Need to check sciter build.

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/actions/runs/10048818493/job/27773596755 ` dpkg-deb: error: 'nasm.deb' is not a Debian format archive`

**Comment by basilgello** [comment]
@21pages This is what it takes to mix curl and wget :D curl has `-o` flag specifying output file, while wget has `-O`. Resolved and please run sciter build once more :)

**Comment by basilgello** [comment]
@deep-soft https://github.com/frankpapenmeier/libyuv/blob/master/docs/getting_started.md see Benchmarking

**Comment by basilgello** [comment]
@21pages x86_64 sciter build succeeds, armv7 runner is probably not available for your account hence the docker build issues caused by `exec format error`.

@rustdesk please merge once 21pages confirms its ok :)

**Comment by 21pages** [comment]
https://github.com/21pages/rustdesk/actions/runs/10051836471/job/27782085305

x64 sciter builds ok and runs fine.

**Comment by 21pages** [comment]
aom-avx2.diff only effect linux sciter?

**Comment by basilgello** [comment]
That patch disables AVX2 feature of libaom if GCC compiler reports it supports `-mavx2` but the include files shipped with it (namely, `emmintrin.h`) dont support 256-bit AVX2 types at all. In current Ruatdesk build infra, only linux sciter build uses GCC7 where such behavior is present. Minimal GCC compiler for libaom >= 3.9.0 is GCC9, but all other compilers are much newer

**Comment by basilgello** [comment]
@rustdesk Once you merge this PR please trigger F-Droid version action. You made a tag but the version did not update because the wrong assumption I made 2 weeks ago

**Comment by rustdesk** [comment]
Got it.

**Comment by rustdesk** [comment]
> only linux sciter

The arm32 or x64 sciter?

**Comment by basilgello** [comment]
It should fix both. But @21pages checked x64 one because his personal account has no ARM64 selfhost runner attached

**Comment by basilgello** [comment]
From comments on 1.2.7 announcement on r/rustdesk:

```
Hopefully this time it will not take weeks till it will also be available on F-Droid.. Thanks for your work guys
```

If you merge this one today and run the action, I can push the update manually.

**Comment by basilgello** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15436

**Comment by rustdesk** [comment]
armv7 failed, https://github.com/rustdesk/rustdesk/actions/runs/10068187573/job/27834343133

**Pull request merged**
