### PR TITLE
README.md Translate Turkish

### PR DESCRIPTION
**Pull request by SnmzMert**

### CODE REVIEW

**Comment by SnmzTony** [comment]
I Translated to Turkish. I happy for help you

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/tree/master/docs

**Comment by SnmzTony** [comment]
Now okey?

**Comment by rustdesk** [comment]
You should not replace README, you should create newfile under docs, just like README-FR.md for french.

**Comment by SnmzTony** [comment]
I did now. Sorry about that.

**Comment by rustdesk** [comment]
Please create new PR with the new file.

**Pull request closed without merging**
