### PR TITLE
Fixes for vcpkg-deps

### PR DESCRIPTION
**Pull request by basilgello**
We switched to unmodified oboe. If that gives weird
errors, we can add oboe.patch into res/vcpkg/oboe.

Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>

### CODE REVIEW

**Comment by basilgello** [comment]
The second patch is an attempt to increase waiting time before the error is thrown from 12 to 128 seconds. In reality, reports show 30 seconds can be enough so lets check.

**Comment by basilgello** [comment]
The last commit builds arm libvpx properly on arm64 machines.

Need merge and manual nightly build to see if all issues gone

**Comment by basilgello** [comment]
And I added github action to publish version info file for F-Droid every time the tag is pushed. F-Droid will read it and update packages automatically.

**Comment by basilgello** [comment]
I am moving oboe_wrapper to separate vcpkg port that will depend on oboe. This way build.rs can be simplified and all the heavy lifting will be done by vcpkg

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/actions/runs/6809018374/job/18514500298 arm-sciter failed. :)

**Pull request merged**
