### PR TITLE
Create es_CT.rs

### PR DESCRIPTION
**Pull request by flusheDData**
New language file for Catalonian

### CODE REVIEW

**Comment by flusheDData** [comment]
> The locale code for the catalan language in Spain is ca_ES

According to  [https://en.wikipedia.org/wiki/Catalonia](https://en.wikipedia.org/wiki/Catalonia)
the ISO 3166 code is ES-CT. I used underscore because of naming consistency.

**Comment by flusheDData** [comment]
Thank you for your help. Changing name.

**Comment by sstepansky** [comment]
> > The locale code for the catalan language in Spain is ca_ES
> 
> According to  [https://en.wikipedia.org/wiki/Catalonia](https://en.wikipedia.org/wiki/Catalonia)
> the ISO 3166 code is ES-CT. I used underscore because of naming consistency. 

That code is for the name of the region, not the language.
https://www.localeplanet.com/icu/ca-ES/index.html

ca_ES is the proper code for the locale. Compare with pt_PT (already in the repo) and pt_BR for example. These distinguish the varieties of Portuguese language spoken in Portugal and Brazil, respectively.

**Comment by flusheDData** [comment]
Thank you.
Renamed.

**Pull request closed without merging**
