### PR TITLE
fix reconnect

### PR DESCRIPTION
**Pull request by 21pages**
1. fix reconnect when reset by the peer
2. fix improper 10054 reconnect

### CODE REVIEW

**Comment by fragtion** [comment]
Today I got the "Connection error" "An existing connection was forcibly closed by the remote host. (os error 10054)" on an already established session that was in viewer mode.  The client did not automatically try to reconnect the session, it had to be done manually. Is there any way to handle this reconnect retrying automatically?

**Comment by 21pages** [comment]
@fragtion when you try to start a connection?

**Comment by fragtion** [comment]
> @fragtion It happened when you try to start a connection?
No, connection was already established for several days. Something caused an interruption (could have been the internet connection) and then the error popped up.  But when this specific error occurs, the client does not try to reconnect automatically. it would be nice to change this behavior if required

Client is the win32 sciter version in this case but I think the same applies for the other builds

**Comment by rustdesk** [comment]
A video please if you want us consider your proposal seriouly. It will help us understand your scenario.

**Comment by 21pages** [comment]
In the current program, when encountering error code 10054, if it is a direct connection and no data is received, it will attempt to relay reconnect. If not, error code 10054 will not trigger a reconnection attempt.

**Comment by fragtion** [comment]
You really need a video as proof that the "Connection error" "An existing connection was forcibly closed by the remote host. (os error 10054)" popup prevents auto-reconnection? C'mon guys.. How will that be different from just sharing a screenshot of the error window? Surely not even a screenshot is necessary for something like this. But fine, I will go through all the effort of reproducing this if that is really what you need

**Comment by fragtion** [comment]
> In the current program, when encountering error code 10054, if it is a direct connection and no data is received, it will attempt to relay reconnect. If not, error code 10054 will not trigger a reconnection attempt.

For the record:
It was a direct IP connection.
It did not attempt to reconnect in any way.

**Comment by rustdesk** [comment]
> different from just sharing a screenshot of the error window

A lot of difference.

**Pull request merged**
