### PR TITLE
Feat/Windows - virtual display privacy mode

### PR DESCRIPTION
**Pull request by fufesou**
1. "Privacy mode", disable physical displays.
2. `check_uac_switch()` in `video_service.rs` is very expensive. Remove the one call in `video_service.rs`.
```rust
        let wait_begin = Instant::now();
        while wait_begin.elapsed().as_millis() < timeout_millis as _ {
            ...
-            #[cfg(windows)]
-            check_uac_switch(c.privacy_mode_id, c._capturer_privacy_mode_id)?;
```
3. Menu on mobile is

4. Change `src/platform/windows.rs`
```rust
        match control_event {
            ServiceControl::Interrogate => ServiceControlHandlerResult::NoError,
            - ServiceControl::Stop => {
            + ServiceControl::Stop | ServiceControl::Preshutdown | ServiceControl::Shutdown => {
                send_close(crate::POSTFIX_SERVICE).ok();
                ServiceControlHandlerResult::NoError
            }
```

https://github.com/rustdesk/rustdesk/assets/13586388/ab614a6d-9a7d-4967-933e-9a0208b95269

https://github.com/rustdesk/rustdesk/assets/13586388/66a55694-534c-4b86-a0ab-84f1691f4f13

## TODOs

If the resolution of the virtual display has been modified, enabling privacy mode will fail.
`ChangeDisplaySettingsEx` will return 2.

I cannot reproduce it anymore.

### CODE REVIEW

**Comment by rustdesk** [comment]
> 5\. Menu on mobile is

There should be seperator line here.

**Comment by rustdesk** [comment]
> > 5. Menu on mobile is
> 
> There should be at least seperator lines here if no better design for secondary level menu.

Pop up  a dialog here since this menu is ugly here.

**Comment by Vasilis553** [comment]
Hello I downloaded the nighly 1.2.4 on windows 10 and on my Android but I don't see the privacy mode options only uses the old method with the layer

**Comment by fufesou** [comment]
This feature has been temporarily removed along with idd.

https://github.com/rustdesk/rustdesk/discussions/6444#discussioncomment-8521217

**Comment by Vasilis553** [comment]
> This feature has been temporarily removed along with idd.
> 
> [#6444 (comment)](https://github.com/rustdesk/rustdesk/discussions/6444#discussioncomment-8521217)
It will come back or you will keep the layer
I though the problem is that the driver don't works fine or it doesn't blacks the physic screen

**Comment by fufesou** [comment]
> I though the problem is that the driver don't works fine

The latest nightly does not contains the driver since https://github.com/rustdesk/rustdesk/pull/7198

> it doesn't blacks the physic screen. Because on this layer has the mouse shown

Yes, it's just a topmost window that hide all others.

**Comment by Vasilis553** [comment]
Is any download link or archive to download older nighly with separate privacy mode and the driver?

**Comment by fufesou** [comment]
The driver is not recommended.

But if you really want that version, you can:
1. Fork this repo.
2. Checkout a new branch based on https://github.com/rustdesk/rustdesk/tree/9a1fd1aa4f98f8b719a8e57b168cb9cda0356896
3. Push to github.
4. Create a nightly tag, push to github.  like https://github.com/fufesou/rustdesk/tree/nightly
5. Create a nightly pre-release.  like  https://github.com/fufesou/rustdesk/releases/tag/nightly
6. Trigger a new action.  like  https://github.com/fufesou/rustdesk/actions/workflows/flutter-nightly.yml

**Comment by Vasilis553** [comment]
> The driver is not recommended.
> 
> But if you really want that version, you can:
> 
> 1. Fork this repo.
> 2. Checkout a new branch based on https://github.com/rustdesk/rustdesk/tree/9a1fd1aa4f98f8b719a8e57b168cb9cda0356896
> 3. Push to github.
> 4. Create a nightly tag, push to github.  like https://github.com/fufesou/rustdesk/tree/nightly
> 5. Create a nightly pre-release.  like  https://github.com/fufesou/rustdesk/releases/tag/nightly
> 6. Trigger a new action.  like  https://github.com/fufesou/rustdesk/actions/workflows/flutter-nightly.yml

Thanks a lot!
And one thing a bug maybe is at nighly v1. 2.4 when you change windows injector.dllfor change the privacy mode image after try to use privacy mode both on remote and on physic stacks on the image instead of remote see the desktop and physic see the image

**Comment by Vasilis553** [comment]
> > The driver is not recommended.
> > But if you really want that version, you can:
> > 
> > 1. Fork this repo.
> > 2. Checkout a new branch based on https://github.com/rustdesk/rustdesk/tree/9a1fd1aa4f98f8b719a8e57b168cb9cda0356896
> > 3. Push to github.
> > 4. Create a nightly tag, push to github.  like https://github.com/fufesou/rustdesk/tree/nightly
> > 5. Create a nightly pre-release.  like  https://github.com/fufesou/rustdesk/releases/tag/nightly
> > 6. Trigger a new action.  like  https://github.com/fufesou/rustdesk/actions/workflows/flutter-nightly.yml
> 
> Thanks a lot! And one thing a bug maybe is at nighly v1. 2.4 when you change windows injector.dllfor change the privacy mode image after try to use privacy mode both on remote and on physic stacks on the image instead of remote see the desktop and physic see the image

ive tryed this but i didnt make it at all do you have the nighly in exe and apk with 2nd privacy mode?

**Pull request merged**
