### PR TITLE
flutter-buid: Parameterize Android builds for easier debug release switch in mirror repos

### PR DESCRIPTION
**Pull request by basilgello**

### CODE REVIEW

**Comment by rustdesk** [comment]
I do not want to publish debug versions in our release to confuse users.

**Comment by basilgello** [comment]
I understand that, but maybe make separate release like `nightly-backupable` and write something like:

```
These builds provide backup and restore functionality using ADB but are less secure than release builds! Use them if you really need backup and restore functionality or automated provisioning of RustDesk Android app!
```

**Comment by basilgello** [comment]
B&R is really needed :(

**Comment by basilgello** [comment]
@rustdesk ^^

**Comment by rustdesk** [comment]
These are adanvaced users, building CI is simple for them.

**Comment by basilgello** [comment]
Yep but maintaining the repo is :) TBH I am not sure Github actions allows to pick only android action from whole flutter build to reproduce official bukld (certs apart ofc)

**Comment by basilgello** [comment]
Maybe (as bare minimum) keep these signed debug builds as artifacts but not let them go in release?

**Comment by rustdesk** [comment]
You can add a secret variable to turn it on. then user can turn it on to build on their repo.

**Comment by basilgello** [comment]
@rustdesk OK I dropped debug builds completely but I would like to have the parameterized build matrix merged because I figured how to transform vanilla `flutter-build.yml` to keep only Android-related jobs omitting others. I will set specific repo and instructions tonight :)

**Comment by rustdesk** [comment]
armv7 android failed, :(

**Comment by basilgello** [comment]
Likely a flake, if it bangs 2nd time I will check :)

**Comment by rustdesk** [comment]
I retried, still failed

**Comment by rustdesk** [comment]
Just retried again, seems working.

**Comment by rustdesk** [comment]
It seems related to Setup `vcpkg with Github Actions binary cache`.

**Comment by rustdesk** [comment]
There must be something we did wrong, https://github.com/rustdesk/rustdesk/actions/runs/10208438546/job/28244926845

**Comment by basilgello** [comment]
Can it be GHA runner cache issue? Because I explicitly set another CI and have got this first and then healed

**Comment by basilgello** [comment]
@rustdesk I found the source of flake.. it is ndk's r27 (clang 18) not playing well with CMake:

```
2024-08-02T09:12:01.3228042Z CMake Error at /usr/local/lib/android/sdk/ndk/27.0.12077973/build/cmake/flags.cmake:46 (if):
2024-08-02T09:12:01.3255182Z ##[error]  if given arguments:
2024-08-02T09:12:01.3255830Z
2024-08-02T09:12:01.3256071Z     "hwaddress" "IN_LIST" "ANDROID_SANITIZE"
2024-08-02T09:12:01.3256080Z
2024-08-02T09:12:01.3256257Z   Unknown arguments specified
2024-08-02T09:12:01.3256440Z Call Stack (most recent call first):
2024-08-02T09:12:01.3256995Z   /usr/local/share/cmake-3.30/Modules/Platform/Android-Clang.cmake:23 (include)
2024-08-02T09:12:01.3257472Z   /usr/local/share/cmake-3.30/Modules/Platform/Android-Clang-C.cmake:1 (include)
2024-08-02T09:12:01.3257918Z   /usr/local/share/cmake-3.30/Modules/CMakeCInformation.cmake:48 (include)
2024-08-02T09:12:01.3258085Z   CMakeLists.txt:7 (project)
```

Also vcpkg did save built libs in cache but never used them to speed up subsequent builds thanks to counter-intuitive `doNotCache: false` needed in each `run-vcpkg` action invocation.

Will PR the fix after I understand what to do.

**Comment by basilgello** [comment]
https://github.com/android/ndk/issues/2032

**Pull request merged**
