### PR TITLE
WIP Trusted clients

### PR DESCRIPTION
**Pull request by grummbeer**
https://github.com/rustdesk/rustdesk/discussions/3988

So far …

- Need feedback and suggestions.
- Need help: How to open a dialog outside the window from which it was called? How do I get it to the center of the screen when I call the dialog from server_page?

### Dialog after "accept"

confirm-dialog-dev

### settings
settings-dev

### settings delete item
settings-delete-dev

- [ ] dialog outside server_page
- [ ] implement at sever_page::handleAccept

### CODE REVIEW

**Comment by rustdesk** [comment]
@dinger1986

**Comment by rustdesk** [comment]
The user probabaly read nothing and click ok again. :(

**Comment by rustdesk** [comment]
> * How to open a dialog outside the window from which it was called? How do I get it to the center of the screen when I call the dialog from server_page?

[AlertDialog](https://api.flutter.dev/flutter/material/AlertDialog-class.html)

**Comment by grummbeer** [comment]
> The users probabaly read nothing and click ok again. :(

… yes … maybe something like this?

two-buttons
two-columns

Is this stuff still a wanted at all?

**Comment by dinger1986** [comment]
So would this show up after giving the other user your ID and one-time password? Or just when they are logging in?

**Comment by grummbeer** [comment]
> So would this show up after giving the other user your ID and one-time password? Or just when they are logging in?

When the other wants to connect, after "accept". Green or blue "accept" (both do the same).

cm

**Comment by rustdesk** [comment]
> When the other wants to connect, after "accept". Green or blue "accept" (both do the same).

Green one will elevate priviledge (windows portable version only).

**Comment by dinger1986** [comment]
I think it should show up but its enough hassle downloading and getting remote software like this installed for genuine clients when doing support we dont want to make it harder, or too much harder.

**Comment by grummbeer** [comment]
> I think it should show up but its enough hassle downloading and getting remote software like this installed for genuine clients when doing support we dont want to make it harder, or too much harder.

Yes. Closing this?

btw, how do your customers know which of the two accept buttons they should click? green or blue?.

**Comment by rustdesk** [comment]
> green or blue?.

Yes, that's a problem, can we call the green one "Accept and Elevate"?

**Comment by dinger1986** [comment]
> > green or blue?.
> 
> Yes, that's a problem, can we rename the green one "Accept and Elevate"? and add tooltip to tell why elevate.

Yeah makes sense

**Pull request closed without merging**
