### PR TITLE
Update de.rs

### PR DESCRIPTION
**Pull request by Mr-Update**

### CODE REVIEW

**Comment by grummbeer** [comment]
@rustdesk the ["Elevate"](https://github.com/rustdesk/rustdesk/blob/master/flutter/lib/desktop/pages/server_page.dart#L577) is used on windows/cm. Can't provoke it right now. 

When is this displayed and what does it mean? In German this one-worder is not common to descripe somthing like "grant access" or "elevate user rights".

Lets give Mister-Update the change to translate this in the right way.

**Comment by rustdesk** [comment]
> "elevate user rights"

Yes, this is better.

**Comment by rustdesk** [comment]
I just googled, it seems "Elevate Privileges" is used more.

**Comment by grummbeer** [comment]
Means change "Elevate" to "Elevate Privileges"? Reset the existing translations for it to ""?
https://github.com/rustdesk/rustdesk/blob/master/flutter/lib/desktop/pages/server_page.dart#L577) 


The translations needs a overhaul.

**Comment by rustdesk** [comment]
No need, "Elevate" is not bad.

**Pull request merged**
