### PR TITLE
fix: Warning: Flutter SVG only supports the following formats for `width` and `height` …

### PR DESCRIPTION
**Pull request by grummbeer**
When opening the file transfer view, the log is filled with:

```
flutter: Warning: Flutter SVG only supports the following formats for `width` and `height` on the SVG root:
  width="100%"
  width="100em"
  width="100ex"
  width="100px"
  width="100" (where the number will be treated as pixels).
The supplied value (32pt) will be discarded and treated as if it had not been specified.
```

Reason: `width="32pt" height="32pt"`

I am using "https://jakearchibald.github.io/svgomg/" for optimizing the svgs and saw this when using the originals:

|||||
|--|--|--|--|
|chat-cutted|arrow-cutted|dots-cutted|dots-cutted-inkscape|

### Before: No visual defect detectable

after

### After:

- No visual defect detectable
- just no more logs
- no longer this "cutted"-thing

before

@NicKoehler, since I'm not that expert on SVG, would be cool if you could review and approve this MR … if you can find time of course.

### CODE REVIEW

**Comment by grummbeer** [comment]
Now There is only one log message left:

```
flutter: unhandled element defs; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#2e079(), name: "assets/arrow.svg", colorFilter: null, theme: SvgTheme(currentColor: Color(0xff000000), fontSize: 14.0, xHeight: 7.0))
flutter: unhandled element sodipodi:namedview; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#2e079(), name: "assets/arrow.svg", colorFilter: null, theme: SvgTheme(currentColor: Color(0xff000000), fontSize: 14.0, xHeight: 7.0))
```

Refers to: https://github.com/dnfield/flutter_svg/issues/98

Something with filters? No idea. @NicKoehler can you have a look on this also?

**Comment by rustdesk** [comment]
let me check, I will remove `pt` warning also.

**Comment by grummbeer** [comment]
@NicKoehler. You are simply the best person with the best knowledge for this topic.

Would you be OK with me considering you as some sort of responsible person for this topic in the future and informing you when changes are made so you can review and confirm/approve?

**Comment by grummbeer** [comment]
> let me check, I will remove pt warning also.

Do! Sharing responsibility is not that bad at all.

**Comment by rustdesk** [comment]
> Now There is only one log message left:
> 
> ```
> flutter: unhandled element defs; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#2e079(), name: "assets/arrow.svg", colorFilter: null, theme: SvgTheme(currentColor: Color(0xff000000), fontSize: 14.0, xHeight: 7.0))
> flutter: unhandled element sodipodi:namedview; Picture key: AssetBundlePictureKey(bundle: PlatformAssetBundle#2e079(), name: "assets/arrow.svg", colorFilter: null, theme: SvgTheme(currentColor: Color(0xff000000), fontSize: 14.0, xHeight: 7.0))
> ```
> 
> ~Refers to: [dnfield/flutter_svg#98](https://github.com/dnfield/flutter_svg/issues/98)~ ~Something with filters?~ No idea.
> 
> @NicKoehler can you have a look on this also?

I can not see this.

**Comment by rustdesk** [comment]
> You are simply the best person with the best knowledge for this topic.

I am most familiar with these svg issues in my team. :)

**Comment by grummbeer** [comment]
> I can not see this log.

Oh! Then I introduced that with this change? Unwanted … something about the optimization?

**Comment by rustdesk** [comment]
> Oh! Then I introduced that with this change? Unwanted … something about the optimization?

I guess so, that svg pub has limit compatibility to svg format.

**Comment by rustdesk** [comment]
Sorry, my new commit to remove `pt` warning causes your conflicts.

**Comment by rustdesk** [comment]
I use svgo command usually. `brew install svgo`.

**Comment by grummbeer** [comment]
> I use svgo command usually

yes, and shame on me, i uploaded the raw files instead the optimized …

**Comment by rustdesk** [comment]
> Do! Sharing responsibility is not that bad at all.

This bothers me every day

**Comment by grummbeer** [comment]
> This bothers me every day

Yes, I understand that 100%. I hope that you might be able to find contributors for your project who will take a kind of responsibility for "their" parts.

**Comment by rustdesk** [comment]
You and @NicKoehler are the best contributors of RustDesk so far. :)

**Comment by grummbeer** [comment]
:-( Oh … that was easy

You can ping me for review and approvment for UX. I'am not a fire and forget guy.

**Comment by rustdesk** [comment]
👍

**Comment by NicKoehler** [comment]
> You and @NicKoehler are the best contributors of RustDesk so far. :)

Thank you for the kind words, I use this software on my daily basis and I'm glad to help in my little free time

> @NicKoehler. You are simply the best person with the best knowledge for this topic.
> 
> Would you be OK with me considering you as some sort of responsible person for this topic in the future and informing you when changes are made so you can review and confirm/approve?

Yes I'll do my best. So this svg issue is something happening only to you?

**Comment by grummbeer** [comment]
> Yes I'll do my best. So this svg issue is something happening only to you?

The second one yes, because i stupildy uploaded the raw files instead the optimized one.

To be clear, I didn't mean that you should help me with my personal problems, but if you would review changes to graphical/visual stuff in general for this project. If changes come in, you get a ping to ensure the change follow the wanted over all style. Something in this kind.

**Pull request closed without merging**
