### PR TITLE
fix: installed, copy&paste, special format

### PR DESCRIPTION
**Pull request by fufesou**
https://github.com/rustdesk/rustdesk/discussions/9568

### CODE REVIEW

**Comment by Paolo-O** [comment]
Thank you very much fufesou.
Unfortunately (probably due to my old age, 70) I have no idea of how to apply the fix or if it will be implemented in a future release.
I tried the overnight 1.3.2 and it was not working as the 1.3.1.
May you please help me?

**Comment by fufesou** [comment]
@Paolo-O Do you use the nightly build as the controlled side?

**Comment by Paolo-O** [comment]
I used the following site:
https://github.com/rustdesk/rustdesk/releases/tag/nightly
Is it the controlled side that you mean?

**Comment by fufesou** [comment]
> https://github.com/rustdesk/rustdesk/releases/tag/nightly

Yes, use this executable on the remote(controlled) side. If you have installed 1.3.1, you need to upgrade to the nightly(1.3.2) version.

If you have an issue when using the nightly build as the controlled side, please also upload a short video if possible.

**Comment by ZarzueloM** [comment]
Hello! I had the same issue with v1.3.1 too. I just updated to v1.3.7, but still have the problem with formulas and when copy/cut a whole column in Excel.

**Comment by fufesou** [comment]
> but still have the problem with formulas and when copy/cut a whole column in Excel.

Hi, I tried copying cells with formulas. It works for me. Maybe there are some cases that need to be improved.
Can you upload a short video so I can understand more about what is going on?



https://github.com/user-attachments/assets/f4d33226-f30c-4cac-933a-24bd6a3c4284

**Pull request merged**
