### PR TITLE
Dialogs. Cleanup request elevation dialog.

### PR DESCRIPTION
**Pull request by grummbeer**
### Changes

- Mouse pointer on option label
- Option label clickable
- Hide inputfields for credentials when option is not choosen
- Options left align
- resuse input fileds from login

### Desktop before

You can fill username but option "ask" is choosen.

desktop-light-before

### Desktop after 

|||
|-- |-- |
|desktop-light-after-1|desktop-light-after-2|
|desktop-dark-after-1|desktop-dark-after-2|

### Mobile before

|||
|-- |-- |
|mobile-light-before|mobile-dark-before|

### Mobile after
|||
|-- |-- |
|mobile-light-after-1|mobile-light-after-2|
|mobile-dark-after-1|mobile-dark-after-2|

### CODE REVIEW

**Comment by grummbeer** [comment]
Before merge, could you please verify that this both dialogs fire up the keyboard on mobile?

mobile-light-before
os-password

**Comment by rustdesk** [comment]
👍

**Comment by grummbeer** [comment]
> Before merge, could you please verify that this both dialogs fire up the keyboard on mobile?

As it is currently, I am not sure if there is a bug. For me, the keyboard does not appear when I click the input field.

**Comment by rustdesk** [comment]
@21pages

**Comment by 21pages** [comment]
Yes, this is a bug, the reason may be the state switching between the soft keyboard and the external keyboard

**Comment by 21pages** [comment]
I'll try to fix it later.

**Comment by grummbeer** [comment]
> You can comment out gFFI.invokeMethod("enable_soft_keyboard", false); in mobile/remote_page.dart for testing.

Works. Found that line four times, keyboard appear … but honestly I do not understand. Commenting out `enable_soft_keyboard` to make the soft keyboard work :-(

**Comment by grummbeer** [comment]
> try to fix keyboard problem at #4580

Thanks.

**Pull request merged**
