### PR TITLE
Fix. Mobile. Remove left label in RDP dialog

### PR DESCRIPTION
**Pull request by grummbeer**
|mobile before| mobile after |desktop still as wanted|
|--|--|--|
|rdp-mobile-before|rdp-mobile-after|rdp-desktop-after|

### CODE REVIEW

**Comment by rustdesk** [comment]
No margin bettwen controls in "mobile after"?

**Comment by grummbeer** [comment]
All multiline dialogs have this look now. :-(


Screenshot_20230303-162157_RustDesk
mobile-now-light

**Comment by grummbeer** [comment]
Before they were underlined and this automaticlly make a visual margin bottom.

**Comment by rustdesk** [comment]
Looks a little wierd without a margin.

image

**Comment by grummbeer** [comment]
To keep the equal look I have added an extra condition for the bottom spacing … in hope of the ability to fix them all in one

```dart
.marginOnly(bottom: isDesktop ? 8 : 0),
```
… crazy but it is a bit of a mess at the moment.

**Comment by grummbeer** [comment]
> Looks a little wierd without a margin.

Absolutly! But what to do? find them all and add margin manually on each?

**Comment by rustdesk** [comment]
That's why I dislike flutter, it is so easy if it is html/css.

**Comment by rustdesk** [comment]
It is also easier if we have a wraper like "EditorGroup", but it seems we do not have.

**Comment by grummbeer** [comment]
> That's why I dislike flutter, it is so easy if it is html/css.

I have learned this also in the meanhwile. It is a shame, can not believe that.


> EditorGroup

maybe a container like this https://stackoverflow.com/questions/53884092/flutter-how-to-set-margin-for-particular-widget-in-a-form must investigate …

The filled came with the modern dialogs, so i guess its defined in the ThemeData. Maybe we could place a `isDesktop` an get them back underlined. A controlled change can then be made afterwards. 

As i statet my willing …

I've already started with a mock for the dialogs, including trying to theme it, but there's a steep learning curve. And a lot I just don't understand :-(

**Comment by grummbeer** [comment]
:-) you know

**Comment by rustdesk** [comment]
Yes, we need thorough test.

**Comment by rustdesk** [comment]
Go ahead, i trust you.

**Comment by grummbeer** [comment]
Merge this, the dialog looks at least then exactly like the others and better than left labeled.

Do you agree with bringing back the underlined version for mobile, which stay as long as a surprise-free design change is possible?

**Comment by rustdesk** [comment]
underlined is ok for me

**Pull request merged**
