### PR TITLE
Added Indonesia Translation

### PR DESCRIPTION
**Pull request by darkterminal**

### CODE REVIEW

**Comment by rustdesk** [comment]
Thanks a lot, but your id.rs is not complete, the more items are in https://github.com/rustdesk/rustdesk/blob/master/src/lang/template.rs

**Comment by rustdesk** [comment]
Thanks a lot

**Comment by darkterminal** [comment]
Hi @rustdesk I just completed the translation. :smile:

**Comment by rustdesk** [comment]
> Hi @rustdesk I just completed the translation. 😄

Thank you.

**Comment by darkterminal** [comment]
Ah... I forgot to add Indonesian Link in main README.md :disappointed:

**Pull request merged**
