### PR TITLE
remove boxed layout of nested option

### PR DESCRIPTION
**Pull request by grummbeer**
see #3257

|inactive state | active state|
|-- |-- |
| boxed-layout-inactive  |   nested-level-options |

### CODE REVIEW

**Comment by rustdesk** [comment]
How does it look like now?

**Comment by grummbeer** [comment]
|inactive state | active state|
|-- |-- |
| boxed-layout-inactive  |   nested-level-options |

**Comment by rustdesk** [comment]
Beautiful

**Comment by rustdesk** [comment]
let me change github/okta icon to white color.

**Comment by grummbeer** [comment]
ok

**Pull request merged**
