### PR TITLE
refact: window frame border

### PR DESCRIPTION
**Pull request by fufesou**
## Changes

1. Refact linux frame border.

Remove custom frame border in `flutter/linux/my_application.cc`

Add radius for windwo frame.

2. Refact windows and macos frame border. Set the border width from `1.0` to `0.0`. To avoid the border from being inconsistent at the corners. The **trade-off** is that the border is less obvious.

```flutter
final kWindowBorderWidth = isLinux ? 1.0 : 0.0;
```

### Limit

As with all remote windows, the borders are not very noticeable against the white background.

#### Before

https://github.com/rustdesk/rustdesk/assets/13586388/6af8f920-d05d-4c6d-af4b-ce046aec8cb9

#### After

https://github.com/rustdesk/rustdesk/assets/13586388/3615c602-cf0d-4b85-93f5-fcdd82a2b407

#### Before

https://github.com/rustdesk/rustdesk/assets/13586388/52342f87-83ca-4040-8608-6f025ca0e72f

#### After

https://github.com/rustdesk/rustdesk/assets/13586388/676c7989-45dc-4f8b-9bc8-6bff8a02563d

#### Before

https://github.com/rustdesk/rustdesk/assets/13586388/877463be-d601-4ae3-ae5e-af49eb7173e9

#### After

https://github.com/rustdesk/rustdesk/assets/13586388/d00429af-3134-4341-b105-b91bf2c0b596

### CODE REVIEW

**Comment by C-O-D** [comment]
There's still something wrong on Linux, no matter what installation or theme I use.  Square background is always visible in the corners. And btw, can the corner radius  be made optional since my theme has square corners and therefore round corners don't fit very well? 

https://github.com/rustdesk/rustdesk/assets/45463988/e3da09b9-cd77-4b11-98b2-4c5608796861

**Comment by fufesou** [comment]
@C-O-D Hi, thanks for your feedback.

> Square background is always visible in the corners.

I'll test and try fix it later.

> And btw, can the corner radius be made optional since my theme has square corners and therefore round corners don't fit very well?

Maybe you could submit a discussion so more people can see it.

**Comment by C-O-D** [comment]
Ok,  thanks for taking care and for the tip 👍

**Comment by C-O-D** [comment]
> @C-O-D Hi, thanks for your feedback.
> 
> > Square background is always visible in the corners.
> 
> I'll test and try fix it later.
> 
> 

Could you fix it in the meanwhile?

**Comment by fufesou** [comment]
Sorry, I forgot about this issue.
I'm working on other important things right now, I'll get back to this issue when I have some free time.

**Pull request merged**
