### PR TITLE
Use JNI MediaCodec-backed hardware codecs on Android (fix some waiting for image)

### PR DESCRIPTION
**Pull request by basilgello**
This is a companion change utilizing https://github.com/rustdesk-org/hwcodec/pull/12

### CODE REVIEW

**Comment by basilgello** [comment]
@21pages @rustdesk

**Comment by 21pages** [comment]
Currently using ndk codec.

https://github.com/FFmpeg/FFmpeg/blob/792a9979ebc678de9b67745027e2c1bfb63e4845/libavcodec/mediacodecenc.c#L197

https://github.com/FFmpeg/FFmpeg/blob/792a9979ebc678de9b67745027e2c1bfb63e4845/libavcodec/mediacodecdec.c#L317

**Comment by basilgello** [comment]
I am doing them now… Average FPS with previous build was 6 fps (SGS23 Ultra / Android 14 as server -> Debian as Client). Now it is 12-22 fps (and is limited by my laptop GPU). Adding VP8 and VP9 solely for Android should bring even more speedup, now building the change

**Comment by basilgello** [comment]
TBH that 3-6 fps made me to dig into that stuff…  I could not believe hwaccel does 6 fps…

**Comment by 21pages** [comment]
You can compare the speed of h264 and h265, others are implemented now.

**Comment by basilgello** [comment]
h265 is not suppoted on my side… So I have to check (and implement) what I have

**Comment by basilgello** [comment]
VP8 also works with 30 fps on my ooold tablet:

**Comment by basilgello** [comment]
I think for Android we can enable all disabled hwaccel codecs and get away with it. For other platforms, it should be as it is now.

**Comment by 21pages** [comment]
This commit do two things.
1. Replace ndk codec with jni codec, need to do some tests.
2. Here is the codec support for andriod:
encode: vpx aom software, ffmpeg h264/h265 mediacodec hardware
decode: vpx aom software, ffmpeg h264/h265 software

`--enable-decoder=vp8...` are software decoders, which are not needed.
If you want to add mediacodec vp8/v9/av1 encoders or mediacodec decoders, you need to change the codec logic and make it work on your device, and ensure zero latency(one in one out) for decoders.

**Comment by rustdesk** [comment]
> I think for Android we can enable all disabled hwaccel codecs and get away with it. For other platforms, it should be as it is now.

Thanks, but I do not want to change default behavior.

**Comment by basilgello** [comment]
Thanks for the insights! If I understand the situation like you do, the ideal way would be:

1. Extend `--get-hwcodec` part to test and cache the codec availability and latency on given device (on first launch by default or on eveey launch if configured for portable uses like AppImage) using both JNI way and mediandk way and selecting most performant one

2. Send that info to peer (alter codec priorities)

3. Once codec is accepted/changed, do what's done now to restart streaming.

This way, the choices would be backed by real tests on the device and user ability to override the order.

As for hwdec VP8 and VP9, I think they are OK to be added if code testing latency is there

**Comment by rustdesk** [comment]
> As for hwdec VP8 and VP9, I think they are OK to be added if code testing latency is there

I think it is not.

**Comment by rustdesk** [comment]
AV1 is very worthwhile, as more and more devices will support AV1.

**Comment by basilgello** [comment]
OK I restored the original contents of the PR splitting the codec addition away. Gonna do some more tests on my spare time but please help me with testers by making a build and asking users to test on Discord.

> not worthwhile when there is

Wrong :) Not only low-end devices might not support h264/265, but according to https://github.com/Parseus/codecinfo the VPx hardware coders offer up to 120 fps @ 4k while 30 fps @ h264. I can provide more info on this matter if interested.

**Comment by rustdesk** [comment]
> developing countries will thank you for :)

We do not work so hard for `thanks` only. :(

**Comment by basilgello** [comment]
> We do not work so hard for thanks only :(

I definitely should stop working like that too, but you know…  personality is hard to change ~~~~

**Comment by basilgello** [comment]
> but please help me with testers by making a build and asking users to test on Discord.

Can this be done by you? We need to ensure JNI vs ndk codecs will not introduce regressions

**Comment by rustdesk** [comment]
> test on Discord.

Useless, very few guys will do

**Comment by basilgello** [comment]
The CI fails because there are two changes as I mention in the very first comment :)

**Comment by rustdesk** [comment]
In theory, ndk codecs is faster than ndk codecs

**Comment by rustdesk** [comment]
> But it might be that passing image data is faster with `JNI`, because we capture screen with java.

@21pages please confirm

**Comment by 21pages** [comment]
Before codec, captured data is converted to yuv in rust.

**Comment by rustdesk** [comment]
> Before codec, captured data is converted to yuv in rust.

If so, the whole codec is working in Rust env. JNI is no reason to be faster.

**Comment by basilgello** [comment]
Somehow the implementation globally available results in `Waiting for image` most of connection attempts… And the logs are uninformative :( As I mentioned before I will do more tests but external extensive testing is really needed. Maybe add "Force use JNI mediacodec for hardware coders" to Android's Display Settings?

**Comment by rustdesk** [comment]
> Waiting for image

JNI fix your `Waiting for image`?

**Comment by basilgello** [comment]
Yep it does, at least 10x less frequently. I did like 30 tests last night :)

**Comment by rustdesk** [comment]
Then, let's do JNI. You have the best reason.

**Comment by basilgello** [comment]
Remember https://github.com/rustdesk-org/hwcodec/pull/12 should be merged too and crate version bumped

**Comment by rustdesk** [comment]
done, I will update cargo.lock then.

**Comment by rustdesk** [comment]
all done now.

**Comment by rustdesk** [comment]
> VP8 also works with 30 fps on my ooold tablet: Screenshot_20240807-185835

I am very impressed by you. :)
image

**Comment by basilgello** [comment]
I am open for new project starting September in case you decide to engage me more on RD :)

**Comment by basilgello** [comment]
BTW the cargo.lock change did not take effect because of caching: https://github.com/rustdesk/rustdesk/actions/runs/10295904624/job/28496411818#step:14:73
Here should be `Compiling: hwcodec` but it is not there.

I decided to check if resulting apk crashes with undefined code but it started normally.
And it appears that `FFI.init()` is called only from `MainService` activity, i.e client mode still operates on ndk codec mode while server one changes to jni.
I will fix it now by adding `FFI.init()` call to MainActivity and ensuring it works.

To make builds happen with updated hwcodec, `rustdesk-lib-cache-*` Github Action caxhes need to be removed. But let's do that fter a follow-up PPR :)

**Comment by basilgello** [comment]
#8991

**Comment by rustdesk** [comment]
I remember android only has h264/h264 hardware encoder, the others are all software, so your FFI.init() on client is useless for the time being. @21pages please confirm.

**Comment by 21pages** [comment]
Yes, only mediacodec h264/h265 encoders.

**Comment by basilgello** [comment]
For now, yes, but AV1 will be added and (maybe) VP8/9 :)

**Comment by 21pages** [comment]
@basilgello Android as the controlled device has many 'waiting for image' issues. Since you can reproduce this issue, I want to get  your help. This is likely due to Android encoding failures. However, if encoding fails, it should automatically disable MediaCodec and switch to software encoding. Can you debug this part? https://github.com/rustdesk/rustdesk/blob/d335cdbb0c9f840f8ad2518497025670b6bc9cf5/src/server/video_service.rs#L943

**Comment by basilgello** [comment]
@21pages Will try!

**Comment by basilgello** [comment]
@21pages One of reasons why fallback silently fails is that the original `handle_video_frame` has no software codec created in `hwcodec.rs`. I have reordered thst code here https://github.com/basilgello/rustdesk/compare/hwcodec-android The hardware decoder works even on my old tab but I have yet to write the code rendering the texture to pixelbuffer (or framebuffer if using GLES3 is not an option!) to make it release-grade

**Comment by 21pages** [comment]
> One of reasons why fallback silently fails is that the original handle_video_frame has no software codec created in hwcodec.rs.

When Android is cotnrolled side, it doesn't relate to Android decoders, here is the fallback workflow:
* negotiated_codec is H264 or H265, and get h264_mediacodec or hevc_mediacodec config successfully, https://github.com/rustdesk/rustdesk/blob/d335cdbb0c9f840f8ad2518497025670b6bc9cf5/src/server/video_service.rs#L759
* Encode fails more than 12 times, clear mediacodec encode config, `run()` function returns.
https://github.com/rustdesk/rustdesk/blob/d335cdbb0c9f840f8ad2518497025670b6bc9cf5/src/server/video_service.rs#L940
https://github.com/rustdesk/rustdesk/blob/d335cdbb0c9f840f8ad2518497025670b6bc9cf5/libs/scrap/src/common/hwcodec.rs#L635
* `run()` function rerun, negotiated_codec is H264 or H265, get h264_mediacodec or hevc_mediacodec config fails,  fallback to libvpx VP9, set negotiated_codec to VP9
https://github.com/rustdesk/rustdesk/blob/d335cdbb0c9f840f8ad2518497025670b6bc9cf5/src/server/video_service.rs#L769
https://github.com/rustdesk/rustdesk/blob/d335cdbb0c9f840f8ad2518497025670b6bc9cf5/src/server/video_service.rs#L720

When "waiting for image" occurs on the Android controlled side, please note the differences compared to the above process.

Here is the test log
```
scrap::common::hwcodec: all codec info: Some(MediaCodecInfos { version: 33, w: 1088, h: 2432, codecs: [MediaCodecInfo { name: "c2.qti.avc.encoder", is_encoder: true, hw: Some(true), mime_type: "video/avc", surface: true, nv12: true, low_latency: None, min_bitrate: 0, max_bitrate: 220000, min_width: 128, max_width: 8192, min_height: 128, max_height: 8192 }, MediaCodecInfo { name: "OMX.qcom.video.encoder.avc", is_encoder: true, hw: Some(true), mime_type: "video/avc", surface: true, nv12: true, low_latency: None, min_bitrate: 0, max_bitrate: 220000, min_width: 128, max_width: 8192, min_height: 128, max_height: 8192 }, MediaCodecInfo { name: "c2.qti.hevc.encoder", is_encoder: true, hw: Some(true), mime_type: "video/hevc", surface: true, nv12: true, low_latency: None, min_bitrate: 0, max_bitrate: 160000, min_width: 128, max_width: 8192, min_height: 128, max_height: 8192 }, MediaCodecInfo { name: "OMX.qcom.video.encoder.hevc", is_encoder: true, hw: Some(true), mime_type: "video/hevc", surface: true, nv12: true, low_latency: None, min_bitrate: 0, max_bitrate: 160000, min_width: 128, max_width: 8192, min_height: 128, max_height: 8192 }] })
scrap::common::hwcodec: e: [CodecInfo { name: "h264_mediacodec", mc_name: Some("c2.qti.avc.encoder"), format: H264, priority: 0, hwdevice: AV_HWDEVICE_TYPE_NONE }, CodecInfo { name: "hevc_mediacodec", mc_name: Some("c2.qti.hevc.encoder"), format: H265, priority: 0, hwdevice: AV_HWDEVICE_TYPE_NONE }]
scrap::common::codec: new encoder: HWRAM(HwRamEncoderConfig { name: "hevc_mediacodec", mc_name: Some("c2.qti.hevc.encoder"), width: 1080, height: 2400, quality: Balanced, keyframe_interval: None }), i444: false
scrap::common::codec: Android screen, fix quality:1
scrap::common::codec: cpu num: 8, cpu loadavg: 0, available memory: 2G, codec thread: 1
hwcodec: [FFMPEG_RAM_ENC] mediacodec codec_name: c2.qti.hevc.encoder
librustdesk::server::service: Enter display service inner loop
librustdesk::server::service: Call snapshot of display service
librustdesk::server::display_service: Displays changed
jni::wrapper::java_vm::vm: Attached daemon thread tokio-runtime-worker (ThreadId(13)). 3 threads attached
librustdesk::server::video_service: start flag is set
librustdesk::server::video_service: hardware: true, scale_soft: true, screen_size: (1080, 2400, 1)
librustdesk::server::video_service: old_scale: 1, new_scale: 1
librustdesk::server::video_service: initial quality: Balanced
librustdesk::server::service: Call snapshot of video0 service
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
librustdesk::server::video_service: err: test
scrap::common::hwcodec: clear hwcodec config, vram: false, encode: true
scrap::common::codec: update:Check
scrap::common::hwcodec: all codec info: None
scrap::common::hwcodec: e: []
scrap::common::hwcodec: all codec info: None
scrap::common::hwcodec: e: []
scrap::common::codec: usable: vp8=true, av1=true, h264=false, h265=false
scrap::common::codec: connection count: 1, used preference: Auto, encoder: VP9
librustdesk::server::video_service: switch due to encoding fails more than 12 times
librustdesk::server::service: Error of video0 service: SWITCH
librustdesk::server::service: Enter video0 service inner loop
librustdesk::server::video_service: #displays=1, current=0, origin: (0, 0), width=1080, height=2400, cpus=8/8, name:Android
librustdesk::server::video_service: Try create capturer with capturer privacy mode id 0
librustdesk::server::video_service: Create capturer from scrap
scrap::common::codec: new encoder: VPX(VpxEncoderConfig { width: 1080, height: 2400, quality: Balanced, codec: VP9, keyframe_interval: None }), i444: false
scrap::common::codec: Android screen, fix quality:1
librustdesk::server::video_service: start flag is set
librustdesk::server::video_service: hardware: false, scale_soft: true, screen_size: (1080, 2400, 1)
librustdesk::server::video_service: old_scale: 1, new_scale: 2
librustdesk::server::video_service: switch due to scale changed, 1 -> 2
librustdesk::server::video_service: Display width: 540 height: 1200 name: "Android" online: true original_resolution {width: 540 height: 1200} scale: 1 changed
librustdesk::server::service: Error of video0 service: SWITCH
librustdesk::server::display_service: Displays changed
jni::wrapper::java_vm::vm: Attached daemon thread tokio-runtime-worker (ThreadId(17)). 4 threads attached
librustdesk::server::service: Enter video0 service inner loop
librustdesk::server::video_service: #displays=1, current=0, origin: (0, 0), width=540, height=1200, cpus=8/8, name:Android
librustdesk::server::video_service: Try create capturer with capturer privacy mode id 0
librustdesk::server::video_service: Create capturer from scrap
scrap::common::codec: new encoder: VPX(VpxEncoderConfig { width: 540, height: 1200, quality: Balanced, codec: VP9, keyframe_interval: None }), i444: false
scrap::common::codec: Android screen, fix quality:4
librustdesk::server::video_service: start flag is set
librustdesk::server::video_service: hardware: false, scale_soft: true, screen_size: (540, 1200, 2)
librustdesk::server::video_service: old_scale: 2, new_scale: 2
librustdesk::server::video_service: initial quality: Balanced
```

**Comment by basilgello** [comment]
@21pages So if I understand your log vs the one from my remote S24 Ultra the ussue is "Error of video0 service: SWITCH" ?

**Comment by 21pages** [comment]
The process is, if the waiting for image is caused by encoding failure, mediacodec will be disabled after reaching 12 times, and then "Error of video0 service: SWITCH", using libvpx vp9. wondering why this process did not happen.

**Comment by basilgello** [comment]
OK, trying with fault injection :)

**Comment by 21pages** [comment]
https://github.com/rustdesk/rustdesk/pull/9242 This may help if waiting for the image is due to encoding/decoding failure.

**Pull request merged**
