### PR TITLE
Refactor vcpkg dependencies and get rid of thirdparty repos

### PR DESCRIPTION
**Pull request by basilgello**
- Fix build on android-x86 and rename function
- Add custom ports not (yet) in upstream vcpkg
- Refactor build_android_deps.sh
- Fix CI

### CODE REVIEW

**Comment by rustdesk** [comment]
👍

**Comment by basilgello** [comment]
@rustdesk How do we trigger CI build for it?

**Comment by rustdesk** [comment]
I think you can trigger nightly build manually

**Comment by rustdesk** [comment]
Please move vcpkg etc to `res/`

**Comment by basilgello** [comment]
I checked Actions tab - there is malformed YAML so the build failed at startup. Starting the fix round :)

**Comment by basilgello** [comment]
Moved vcpkg folder to res - vcpkg.json should stay in project root because there you declare project-wude dependsncies for all platforms. In manifest mode, vcpkg installs deps not into `$VCPKG_ROOT/installed` but into `./vcpkg-installed`.

**Comment by rustdesk** [comment]
Thanks

**Comment by basilgello** [comment]
Fixed :)

**Comment by rustdesk** [comment]
@basilgello Great job. Have you run nightly build? since the regular CI does not run ios/arm-linux job.

**Comment by rustdesk** [comment]
To run arm-linux, you must remove this line https://github.com/rustdesk/rustdesk/blob/27112e348040e707ff977025ed1b6a494a0107d5/.github/workflows/flutter-build.yml#L811
we used our selfhost runner for speed.

**Comment by basilgello** [comment]
I have not run nightly yet but from error message https://github.com/rustdesk/rustdesk/actions/runs/6757946924/job/18369867841 it was due to old Dart SDK version. I bumped that, too. Now as flutter-elinux is 3.13.9 (same as flutter), do we still need to patch arm64 engine? https://github.com/rustdesk/rustdesk/pull/6282/files#diff-3956b537fa0feef7331e9ec28b3a40d35aea3e7f0d801a980ae073d3316ebe05R1437

**Comment by rustdesk** [comment]
> it was due to old Dart SDK version. I bumped that, too. Now as flutter-elinux is 3.13.9 (same as flutter)

Great, Thanks

**Comment by rustdesk** [comment]
> do we still need to patch arm64 engine?

No need any more.

**Comment by basilgello** [comment]
Ah, OK :) Will fix it now and run

**Comment by basilgello** [comment]
And I upstreamed aom vcpkg port. Should be added shortly :)

**Comment by basilgello** [comment]
So far, sciter-armv7 builds, aarch64 libs fall out of memory on github runner and arm64-ios in libvpx still produces wrong ELFs. I will spin macos-latest runner to see why. Maybe it is better to add manual workflow so you can trigger the nightly build on selfhosted runners and we dont wait 5h?

**Comment by rustdesk** [comment]
I can manually trigger nightly build.

**Comment by basilgello** [comment]
OK, now I removed the temp commit and added skip CI until I fix arm64-ios. Then I force-push once more and ask you to trigger manual nightly build. No need to waste resources now :)

**Comment by rustdesk** [comment]
Agree, 👍

**Comment by rustdesk** [comment]
Ready for merge?

**Comment by basilgello** [comment]
https://github.com/basilgello/rustdesk/actions/runs/6781699300

**Comment by basilgello** [comment]
Also, I see that mostly everywhere we regenerate bridge files despite bridge cache is restored.

**Comment by rustdesk** [comment]
> Also, I see that mostly everywhere we regenerate bridge files despite bridge cache is restored.

Yes, this part is also ugly.

**Comment by basilgello** [comment]
I will fix it but what do you prefer: build that bridge first and restore everywhere or build everywhere and drop the bridge step? I think build once reuse everywhere is better

**Comment by rustdesk** [comment]
> I think build once reuse everywhere is better

Yes, I do not know if bridge on Windows can be used on Linux.

**Comment by rustdesk** [comment]
mac/ios can do share the same bridge.

**Comment by basilgello** [comment]
Bridge files are source files, so in theory they are portable across architectures. We can test it on CI :) If build fails, they are not portable. If succeeds, we can drop rebuilds altogether.

**Comment by basilgello** [comment]
Ah… That `cargo expand` issue?

**Comment by rustdesk** [comment]
> Ah… That `cargo expand` issue?

Yes, exactly.

**Comment by basilgello** [comment]
Then I think it is better to comment rebuild actions **for now** and once we figure out how to migrate codegen to 1.82.3+, we will drop the caching state and uncomment the rebuild actions.

Makes sense?

**Comment by rustdesk** [comment]
Agree, if CI can pass.

**Comment by rustdesk** [comment]
BTW, mac/ios requires this file `./macos/Runner/bridge_generated.h`,  `./ios/Runner/bridge_generated.h`, the other does not.

**Comment by basilgello** [comment]
Building librustdesk on arm64-ios fixed: https://github.com/basilgello/rustdesk/actions/runs/6781866871

Commenting rebuild actions, pushing once more without CI

**Comment by basilgello** [comment]
Pushed! If you wantwe can wait for CI or you cancel CI run and manually trigger nightly build

**Comment by basilgello** [comment]
And cancel CI run gor a merge ;) And restart sciter run - it is some glitch with git pull

**Comment by rustdesk** [comment]
Nightly build is running now. :)

**Comment by rustdesk** [comment]
Arm failed, https://github.com/rustdesk/rustdesk/actions/runs/6782621006/job/18435284343

**Comment by basilgello** [comment]
Moment :) zip is missing? Let me add one in a new PR

**Comment by basilgello** [comment]
#6318

**Comment by rustdesk** [comment]
failed again

**Comment by basilgello** [comment]
This time cmake :) Why vcpkg lists only haf of basic deps needed? :) Will pr there too

**Comment by basilgello** [comment]
#6319

**Comment by basilgello** [comment]
Moment :) What a wild ride :D

**Comment by basilgello** [comment]
#6320

**Comment by rustdesk** [comment]
Failed, :)

**Comment by basilgello** [comment]
Dont cancel the whole run please - I want to make sure aarch64 and ipa build. I am spawning another test for arm-linux on aarch64 (I did test cross-building from x86_64 to arm-linyx so maybe I missed something)

**Comment by rustdesk** [comment]
Got it.

**Comment by basilgello** [comment]
Ha, darwin (macos) decided it does not want to let DMG go :) Glitch

**Comment by rustdesk** [comment]
:(

**Comment by basilgello** [comment]
Aaaand ios failed with totally unexpected error: https://github.com/rustdesk/rustdesk/actions/runs/6783095255/job/18436731959#step:12:99 It looks like we should not use linux bridge for macos either (but you warned me :) )

**Comment by basilgello** [comment]
Looks like the opposite should be done to what I did in https://github.com/rustdesk/rustdesk/commit/f0f52d72448893b2d8e33a1304d92d8194fd4c47 Dont revert yourself, I will push all fixes in separate PR

**Comment by basilgello** [comment]
And very strange errors here: https://github.com/rustdesk/rustdesk/actions/runs/6783095255/job/18438768047#step:6:757 The library was successfully built, but prebuilt flutter can not be executed.

That self-hosted runners - are they native aarch64 or amd64? Looks like they are native ARM and you use docker with amd64 to build rustdesk. Is that correct?

**Comment by rustdesk** [comment]
my self-hosted runner is aarch64.

**Comment by rustdesk** [comment]
I noticed you removed elinux, I thought you got better solution, so did not warn you.

**Comment by basilgello** [comment]
I likely mixed removing this: https://github.com/rustdesk/rustdesk/blob/97aeee71724e39de35712d25aafc22dbfbc8cf09/.github/workflows/flutter-build.yml#L1445 with removing elinux as a whole.

**Comment by basilgello** [comment]
#6323

**Comment by basilgello** [comment]
Pushed the reverts, and the only remaining thing is libvpx ( again :( )

**Comment by basilgello** [comment]
apk is unusable because prebuilt liboboe.a from thirdparty_lib was silently patched with `create_oboe_player` / `push_oboe_data` / `destroy_oboe_player`. Introducing `oboe_wrapper` again as we copy libc++ anyway :)

**Comment by basilgello** [comment]
sciter build likely fails because of caches. If we could delete `libvpx-7f3876922f77d20fe5f48b5d90e8b7fb609cd6739bf4005f696a024438b665be`, `libvpx-5dc1b5311282808b03b9efbe766ba49d8d8731cba002fdcbeef71ffed0ff9ba2`,`libvpx-084bf404f4053b8d600f40d601bb6f3dfb5b150228438ebf01df381ec42d3bea` from https://github.com/rustdesk/rustdesk/actions/caches the libvpx would be rebuilt for arm-linux using latest fixed script. For macos failure, I will do follow-up PR. Android APKs are useful again :)

**Comment by rustdesk** [comment]
Let me clean cache and try again.

**Comment by basilgello** [comment]
#6358 for test - merge, start nightly build and revert afterwards :) Otherwise I cant reproduce the faulty rlib :(

**Comment by sahilyeole** [comment]
@basilgello I'm not able to install the nightly .rpm build on fedora.
Please check it or let me know if I'm missing some dependency.

```bash
$ sudo dnf localinstall rustdesk-1.2.4-0.x86_64.rpm 
Last metadata expiration check: 2:06:09 ago on Sunday 12 November 2023 02:19:17 AM.
Error: 
 Problem: conflicting requests
  - nothing provides libfile_selector_linux_plugin.so()(64bit) needed by rustdesk-1.2.4-0.x86_64 from @commandline
(try to add '--skip-broken' to skip uninstallable packages)
```
No problem with 1.2.3

**Comment by basilgello** [comment]
The library is inside the rpm @sahilyeole :) Trying to understand why rpm declared it as external dependency.

**Comment by basilgello** [comment]
```diff
[root@82e5b92284ec /]# diff -ru --color requires.*
--- requires.123        2023-10-13 00:00:00.000000000 +0000
+++ requires.124        2023-11-12 00:00:00.000000000 +0000
@@ -16,6 +16,7 @@
 libdesktop_multi_window_plugin.so()(64bit)
 libdl.so.2()(64bit)
 libdl.so.2(GLIBC_2.2.5)(64bit)
+libfile_selector_linux_plugin.so()(64bit)
 libflutter_custom_cursor_plugin.so()(64bit)
 libflutter_linux_gtk.so()(64bit)
 libgcc_s.so.1()(64bit)
```

**Comment by basilgello** [comment]
@sahilyeole #6384 :)

**Pull request merged**
