### PR TITLE
feat, multi_flutter_ui_sessions

### PR DESCRIPTION
**Pull request by dignow**
https://github.com/rustdesk/rustdesk/issues/486

## Main changes

1. Support multiple screen capture on the server side. 
2. Support screen merging.

## Unsupported

1. Screen merging, sciter version.
2. Multiple screen capture, wayland.
3. Multiple screen capture, privacy mode.

## Tests

- [x] The control side, windows, linux, macOS.
- [x] Multi screen on windows, linux, as the controlled side.
- [ ] Multi screen on macOS, as the controlled side.
- [x] Compatible with old version.
- [x] "Scale Original", "Scale Adaptive" and scroll style.

https://github.com/rustdesk/rustdesk/assets/136106582/ed476a8f-74a9-49ed-81d7-454103b84927

https://github.com/rustdesk/rustdesk/assets/136106582/010138d9-813f-42b3-8eeb-20f3049628ef

The flutter ui session hierarchy is a bit complicated now.

flutter-session-hierarchy

## Note

The Win -> Win is the latest version. The option is refactored.

## TODOs
1. Open N windows, in different monitors or positions. Each window show each monitor.

### CODE REVIEW

**Comment by SergeyMy** [comment]
this is cool, when will it be released?

**Comment by deep-soft** [comment]
Tested on windows host with windows remote, works as intended.

**Comment by SergeyMy** [comment]
didn't work :(

```
~/.cargo/bin/flutter_rust_bridge_codegen --version
flutter_rust_bridge_codegen 1.75.3

```
flutter_rust_bridge_codegen ...

```
These packages are no longer being depended on:
- screen_retriever 0.1.9
Changed 1 dependency!
```

```
Running build_runner at /home/virtual/SRC_SSD/rustdesk/flutter
Unhandled exception:
Null check operator used on a null value
#0      PackageGraph.forPath.<anonymous closure> (package:build_runner_core/src/package_graph/package_graph.dart:106:72)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:31)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#3      List.addAll (dart:core-patch/growable_array.dart:325:17)
#4      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:106:12)
<asynchronous suspension>
#5      main (file:///home/virtual/.pub-cache/hosted/pub.dev/build_runner-2.4.6/bin/build_runner.dart:27:30)
<asynchronous suspension>
2023/10/13 19:22:49 [WARN] command=cd "/home/virtual/SRC_SSD/rustdesk/flutter" && "sh" "-c" "\"flutter\" \"pub\" \"run\" \"build_runner\" \"build\" \"--delete-conflicting-outputs\"" stdout= stderr=
2023/10/13 19:22:49 [ERROR] fatal: Failed to run build_runner for /home/virtual/SRC_SSD/rustdesk/flutter:
```

**Comment by SergeyMy** [comment]
What have I done wrong? :(

https://github.com/rustdesk/rustdesk/assets/131688106/6ac74660-17c4-4ec7-a299-406d574736e4

**Comment by dignow** [comment]
> where is this thing изображение

@SergeyMy 

The option is moved to

**Comment by SergeyMy** [comment]
@dignow 
изображение

**Comment by dignow** [comment]
> the button will not appear if there is one monitor on the other side, or (and) an old client?

If the remote side has only one monitor, the buttons to choose display will not show.
If the remote side is old version, merged monitor and open in seperate window will not work.

**Comment by SergeyMy** [comment]
thanks, I knew/suspected it, but clarified it

**Comment by SergeyMy** [comment]
Well, an abstract question: is it really not necessary to update hbb_common on the hbbr hbbs server?
изображение

**Comment by rustdesk** [comment]
@fufesou resolve the confilicts, I will merge

**Comment by SergeyMy** [comment]
@fufesou @rustdesk It’s high time to upgrade the release version, a lot of changes have accumulated

**Comment by SergeyMy** [comment]
@dignow @rustdesk 
everything disappeared in the release :( no:
**Show displays as individual windows**

**Comment by dignow** [comment]
@SergeyMy Thanks for the feedback.

With **Show displays as individual windows**

Everytime you open a new window, the window is black ?

Will the images come back after "Refresh"?

**Comment by dignow** [comment]
@SergeyMy Do you build without the `flutter_texture_render` feature? I've fixed some bugs.

https://github.com/rustdesk/rustdesk/pull/6047

**Comment by hlblade** [comment]
Thanks very much for your great work!
Is it workable to use multi screen as client side? like use microsoft mstsc "use all my monitor in the remote connection"

**Comment by dignow** [comment]
https://github.com/rustdesk/rustdesk/pull/6064

But RustDesk will not create virtual display if local monitor's number is greater.

**Comment by deep-soft** [comment]
Tested on Windows 11 (rustdesk 1.2.4) to Windows 11 (rustdesk 1.2.4 with 2 monitors):
1. on rustdesk client: General > Other > "Open connection in new tab" is unchecked (each connection run's in it's own window)
2. initial connection to rusdesk server (rustdesk 1.2.4 is installed, run's as service), monitor 1 active
3. click on remote toolbar, 2nd monitor, new window is created, monitor 2 is active
4. changing from window 2 to window 1, working inside every window with mouse and/or keyboard ... works ok.
5. I choose not to close any of the two sessions, instead I choose (from the remote toolbar on window 1 or 2) "View mode"
6. "View mode" is checked on active window but not in the other one, see pictures.
7. if I choose "View mode" on the other window the "View mode" is checked in this window but in fact I can type in both windows and/or click with mouse inside both windows.
8. if  "View mode" option was intended per window (session) in fact this has efect on the other window, but without activate the check on  "View mode" option in other window.
image
image

**Comment by rustdesk** [comment]
@deep-soft https://github.com/rustdesk/rustdesk/pull/7247 please test tommorrow's nightly build

**Comment by deep-soft** [comment]
Tested on the same conditions as:
https://github.com/rustdesk/rustdesk/pull/5945#issuecomment-1957640373

Now the options are in sync, change in window 1 (session 1), same change in window 2 (session 2) and viceversa.

Thanks for this PR!

**Pull request merged**
