### PR TITLE
Fix/enable menu before image

### PR DESCRIPTION
**Pull request by fufesou**
https://github.com/rustdesk/rustdesk/issues/5488

1. Enable remote toolbar after connection is established and before the image. 

`flutter/lib/desktop/pages/remote_page.dart`

https://github.com/rustdesk/rustdesk/assets/13586388/2ee39025-8ab1-4654-8a4b-0bff05977d99

`flutter/lib/models/model.dart` is also modified for 

```dart
          Obx(
            () => _ffi.ffiModel.waitForFirstImage.isTrue
                ? emptyOverlay()
                : Offstage(),
          ),
```

2. Wrap the remote toolbar with Overlay, to enable rebuild every time on expanding the menu. And so the menu can use the latest configurations.
The master branch also wraps the remote toolbar with Overlay. And the remote image body is also wrapped in an Overlay.

https://github.com/rustdesk/rustdesk/assets/13586388/fdd500c5-6ea2-4508-8b78-c30e5e82f33d

3. Right menu duration from 4s to 300s.

`flutter/lib/desktop/widgets/tabbar_widget.dart`

### CODE REVIEW

**Comment by SergeyMy** [comment]
merge with the master - I'll check :)

**Comment by SergeyMy** [comment]
@fufesou 
something doesn't work for me  :cold_sweat:

https://github.com/rustdesk/rustdesk/assets/131688106/37c127ab-e8c5-472a-a7aa-64d1248c393b

**Comment by fufesou** [comment]
Yes, the remote menu toolbar is not available  when the status is "Connecting...".
The remote menu toolbar is available on the next state "Connected, waiting for image...".

**Comment by SergeyMy** [comment]
I have in this place
"Connected, waiting for image...". no pause at all
Thank you

**Comment by rustdesk** [comment]
@SergeyMy can you help to verify if you can reproduce this, https://github.com/rustdesk/rustdesk/issues/4657

**Comment by SergeyMy** [comment]
only linux-linux, I don't have windows at all

**Comment by SergeyMy** [comment]
@rustdesk bug not confirmed

https://github.com/rustdesk/rustdesk/assets/131688106/38388ab1-7d4b-4a4d-aaea-04992bf0c00b

**Pull request merged**
