### PR TITLE
install ffmpeg lib with vcpkg

### PR DESCRIPTION
**Pull request by 21pages**
* Use vcpkg to install ffmpeg and build sdk from source, so no prebuild lib in hwcodec.
* Link ffmpeg in rustdesk directly, ffmpeg can be used as basic library.
* For windows developers, `VCPKG_DEFAULT_HOST_TRIPLET` env need to be set to `x64-windows-static` during installation.
* Most code in `res/vcpkg/ffmpeg` is from https://github.com/microsoft/vcpkg/tree/2024.06.15/ports/ffmpeg
* Tested windows/mac/linux/android, still work

### CODE REVIEW

**Comment by rustdesk** [comment]
@basilgello can we enable hwcodec for fdroid?

**Comment by basilgello** [comment]
Yes! @21pages does this imply libamf/libmfx are also installed from vcpkg now? I noticed rust-webm crate also builds libwebp from webm project. Maybe you can move it to vcpkg too?

**Comment by basilgello** [comment]
BTW @rustdesk 1.2.6 was finally built and today it should become available to F-Droid public!

**Comment by basilgello** [comment]
The vcpkg ffmpeg port depends on amd-amf, ffnvcodec and mfx-dispatch. Are you sure building amf from source in rust crate is still needed?

**Comment by 21pages** [comment]
Yes, vcpkg build the core code used by ffmpeg, there are some extra code used by sdk vram codec.

**Comment by basilgello** [comment]
I think we can kang amd-amf port from vcpkg and add custom patches into it. Do you need my help with that?

**Comment by 21pages** [comment]
Can you tell why this is better?

**Pull request merged**
