### PR TITLE
Ipv6

### PR DESCRIPTION
**Pull request by fufesou**
https://github.com/rustdesk/rustdesk-server/pull/119

## Not Sure
1. Why not [drop socket](https://github.com/fufesou/rustdesk/blob/5a9d8545d801b6038acca6c97def9487a4361809/src/server.rs#L86) earlier?
2. If `rendezvous_addr` is a domain string. [`register_pk`](https://github.com/fufesou/rustdesk/blob/5a9d8545d801b6038acca6c97def9487a4361809/src/rendezvous_mediator.rs#L459) use [domain url](https://github.com/fufesou/rustdesk/blob/5a9d8545d801b6038acca6c97def9487a4361809/src/rendezvous_mediator.rs#L153)  to send a udp request. The rendezvous server may see an IPv6 or IPv4 address by occasionally.
  It may be caused by my cloud network provider.
  But it won't take any problems. The only result is from IPv6 --> IPv6 to IPv4 --> IPv4.
3. Comment the [checking socket addr](https://github.com/fufesou/rustdesk/blob/5a9d8545d801b6038acca6c97def9487a4361809/src/rendezvous_mediator.rs#L379) logic.

## Known issues
1. Some private IPv6 is an one-way link. Only relay connection be established on those cases.
2. No considerations about multiple network interfaces.
3. Socks proxy does not support IPv6.

### CODE REVIEW

**Comment by Avey777** [comment]
这个是代表已经支持ipv6  远程控制了吗？

**Comment by fufesou** [comment]
> 这个是代表已经支持ipv6 远程控制了吗？

Yes, it basically works.  I've tested with my cloud network.
But it's still experimental. More cases need to be tested. And there are some uncertainties.

**Comment by Avey777** [comment]
> > 这个是代表已经支持ipv6 远程控制了吗？
> 
> Yes, it basically works. I've tested with my cloud network. But it's still experimental. More cases need to be tested. And there are some uncertainties.

我要怎么尝试使用ipv6呢？ 目前我安装的是V1.1.9版本 。 我没有找到更新的版本了   但这个版本是不能使用 ipv6 的

**Comment by fufesou** [comment]
> 我要怎么尝试使用ipv6呢？ 目前我安装的是V1.1.9版本 。 我没有找到更新的版本了 但这个版本是不能使用 ipv6 的

IPv6 requires both server https://github.com/rustdesk/rustdesk-server/pull/119 and client support. You need to setup your server with https://github.com/rustdesk/rustdesk-server/pull/119 and build rustdesk with this PR.

**Comment by Kristories** [comment]
> 这个是代表已经支持ipv6 远程控制了吗？

Can we use English here? So, we can easily understand it.

**Comment by rustdesk** [comment]
Todo:

[] inclined to choose ipv4 first, only choose ipv6 if any side does not support ipv4.

**Review by Leerusty0 — CHANGES_REQUESTED** [review]
- # **fufk this**

**Comment by rustdesk** [comment]
- [ ] NAT64 handeling
- [ ] for best compatibility before full test, please prioritize v4 for the time being

**Pull request closed without merging**
