### PR TITLE
Feat/linux virtual display (headless linux)

### LINKED ISSUE #3592: Unable to connect to ubuntu with dummy display. (Ver 1.2.0)
### Bug Description

I use Rustdesk to connect to the virtual display of the ubuntu server I usually use and to exchange files.
I had no problems with this when I was using Rustdesk 1.1.9.
I updated to nightly to try a new element.
I have been unable to connect to this device with the message "Reset by the peer".
This problem did not occur when other devices connected to each other or when this device connected to other devices.
Also, the connection to the environment without the dummy display, which was created separately, worked without any problem.
We therefore assumed that the dummy display was the cause of the problem.

1.When you try to connect, a window appears momentarily asking if the connection is possible.
2.The server status display changes momentarily to "Not ready. Please check your connection."
3.The password on the remote side is forcibly reset.

This suggests that the dummy display is causing some problem, leading to the "reset on the other side" message.

[rustdesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/10941873/rustdesk_rCURRENT.log)

### How to Reproduce

1.Install dummy driver.
```
# apt-get install xserver-xorg xserver-xorg-video-dummy
```
2.Put the right configurations in the right places.
```
# vim /etc/X11/xorg.conf
```
The config contents are on [my gist.github.com](https://gist.github.com/j7b3y/ad33a48bad815310697d33d50badcb49#file-xorg-conf)
3.Start the virtual display with the startx command.
```
startx -- :0
```
4.Run Rustdesk
```
DISPLAY=:0 rustdesk
```

### Expected Behavior

I honestly don't know, as I didn't have this problem in 1.1.9.

### Operating system(s) on local side and remote side

Windows 11 > Ubuntu 22.04 LTS

### RustDesk Version(s) on local side and remote side

1.2.0 > 1.2.0

### Screenshots

image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fufesou**
1. Linux virtual display support. https://github.com/rustdesk/rustdesk/issues/59
2. May fix https://github.com/rustdesk/rustdesk/issues/3592.
3. Refactor dialog. https://github.com/rustdesk/rustdesk/pull/3764#issuecomment-1482636535 @grummbeer 
4. Add "--cm-no-ui" for virtual display. There's some `segfault` bug with "--cm" with ui on headless env.

**Only tested on Ubuntu for now.**

Prerequirements:
```bash
# Only support gnome desktop. https://www.gnome.org
# xfce4 may be supported.

# for Ubuntu
$ sudo apt install ubuntu-desktop
$ sudo apt install xserver-xorg-video-dummy
$ sudo apt install lightdm

# for Fedora
$ sudo sudo yum groups install "GNOME"
$ sudo yum install xorg-x11-drv-dummy

# for archlinux
$ pacman -S xorg xorg-server xf86-video-dummy
$ pacman -S gnome

```

Steps
```
# install rustdesk
# get rustdesk id
$ sudo rustdesk --get-id
# set password
$ sudo rustdesk --password <password>

# connect
```

TODOs:
- [ ] Do not show "Connection Error" on logout.
- [ ] Failed to start Xorg on some PCs. `parse_vt_settings: Cannot open /dev/tty0 (Permission denied)`.

### CODE REVIEW

**Comment by grummbeer** [comment]
Wow huge!

@fufesou very nice! 

### 1. dialog 

There must be a bit more space between the sections. Don't bother, i will fix this!

desktop-dark-password-required-linux-headless-before


### 2. docs

Docs needs to be updated, due `libpam0g-dev`, build feature `linux_headless`?

### 3. notes

You split the large dialog Widget into much more smaller parts, what looks very good!

Do you think the same could be done with other very large and cluttered widgets? And also with huge files?

**Comment by congzhangzh** [comment]
cool

**Comment by grummbeer** [comment]
> There must be a bit more space between the sections. Don't bother, i will fix this!

nope … so nice :-) it is, but missed it because i faking the controller to make the os login visible.

**Comment by grummbeer** [comment]
OK, thanks.

**Comment by ManuLinares** [comment]
How can I try this? I'm on rustdesk-nightly, running Arch with XFCE and lightdm.

This is the systemd service file:

```
# ~ cat /usr/lib/systemd/system/rustdesk.service

[Unit]
Description=RustDesk
Requires=network.target
After=systemd-user-sessions.service

[Service]
Type=simple
ExecStart=/usr/bin/rustdesk --service
PIDFile=/run/rustdesk.pid
KillMode=mixed
TimeoutStopSec=30
User=root
LimitNOFILE=100000

[Install]
WantedBy=multi-user.target
```

**Comment by joeySeal** [comment]
"xfce4 may be supported" does this mean xfce might work or xfce might be supported in the future?

**Comment by adamency** [comment]
Got it perfectly working on:

- Arch Linux
- X11
- `xf86-video-dummy` driver
- i3
- lightdm display manager

For about 6 months now. Either on public rustdesk servers or self-hosted.

So being on `gnome` and/or Ubuntu is absolutely unneeded. Basically any Linux system on X11 with the mentioned driver will work, provided nothings goes in the way. That should make every Linux user happy 😄🚀 ! 

PS: While teamviewer doesn't even work on this setup, it doesn't detect any display as soon as I unlock the session on the LightDM screen. This really feels great ! Thanks @rustdesk !

**Comment by lounging-lizard** [comment]
I was able to get this working for Ubuntu 22.04.03 LTS by using the following xorg config (inserted at `/usr/share/X11/xorg.conf.d/xorg.conf`).

I had to create the config file as it was missing, I hope this helps someone else.

This is for a 1920x1080 display via X11/xorg, 

`Section "Device"
  Identifier "Configured Video Device"
  Driver "dummy"
  VideoRam 16384
EndSection

Section "Monitor"
  Identifier "Configured Monitor"
  HorizSync 5.0 - 1000.0
  VertRefresh 5.0 - 1000.0
  ModeLine "1920x1080" 23.53 1920 1952 2040 2072 1080 1106 1108 1135
EndSection

Section "Screen"
  Identifier "Default Screen"
  Monitor "Configured Monitor"
  Device "Configured Video Device"
  DefaultDepth 24
  SubSection "Display"
    Depth 24
    Modes "1920x1080"
  EndSubSection
EndSection
`

For further details regarding Xorg configuration please see: https://wiki.archlinux.org/title/xorg

**Comment by enc2586** [comment]
> I was able to get this working for Ubuntu 22.04.03 LTS by using the following xorg config (inserted at `/usr/share/X11/xorg.conf.d/xorg.conf`).
> 
> I had to create the config file as it was missing, I hope this helps someone else.
> 
> This is for a 1920x1080 display via X11/xorg,
> 
> ```
> Section "Device"
>   Identifier "Configured Video Device"
>   Driver "dummy"
>   VideoRam 16384
> EndSection
> 
> Section "Monitor"
>   Identifier "Configured Monitor"
>   HorizSync 5.0 - 1000.0
>   VertRefresh 5.0 - 1000.0
>   ModeLine "1920x1080" 23.53 1920 1952 2040 2072 1080 1106 1108 1135
> EndSection
> 
> Section "Screen"
>   Identifier "Default Screen"
>   Monitor "Configured Monitor"
>   Device "Configured Video Device"
>   DefaultDepth 24
>   SubSection "Display"
>     Depth 24
>     Modes "1920x1080"
>   EndSubSection
> EndSection
> ```
> 
> For further details regarding Xorg configuration please see: [wiki.archlinux.org/title/xorg](https://wiki.archlinux.org/title/xorg)

Still working on Sep 17, 2025. Thanks.

**Comment by calcioscacchi** [comment]
Hi guys, 

what about debian users?

**Pull request merged**
