### PR TITLE
Url link

### PR DESCRIPTION
**Pull request by paspo**
Support for rustdesk: type links. E.g.    rustdesk:123456789
When you click this link, it should open rustdesk and start a connection.

At the moment, I have linux support and I'm working on windows/osx.

This also fixes a misused `Version` key in `rustdesk.desktop` file.

### CODE REVIEW

**Comment by rustdesk** [comment]
Thanks

**Comment by paspo** [comment]
@rustdesk A better approach than my link-handler would be accepting a command line argument like `rustdesk --connect rustdesk:123123` in addition to `rustdesk --connect 123123` to start the connection right away. This will be very handy in windows also.

**Comment by paspo** [comment]
Windows should be covered now.

**Comment by paspo** [comment]
@rustdesk I need to change the Info.plist inside the MacOS Application. Can you point me to where this file gets generated?

**Comment by rustdesk** [comment]
build.py

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/blob/master/build.py#L182

**Comment by paspo** [comment]
OK, now the .plist modification is opening the app, but there's more to do: we need to implement a delegate to handle the url.
Sadly I found only ObjC and swift code ([example](https://css-tricks.com/create-url-scheme/), but not rust. 
@rustdesk, can you help?

**Comment by rustdesk** [comment]
Sure, but low priority.

**Comment by rustdesk** [comment]
And, we are rewriting UI with flutter now, I guess there is delegate in flutter, @Kingtous

**Comment by Kingtous** [comment]
Let's see whether there is a way to handle the url link on Flutter level.

**Comment by gljones2001** [comment]
How far along is this? I would live to test it's compatibility with GLPI. We use RustDesk here at my job, and I have been setting up GLPI for inventory in IT and it would be cool to be able to remote in with one click. 

@paspo what do I setup in GLPI for it to grab the RustDesk ID from each PC? I cant seem to get it to.

@rustdesk If you need another tester for RustDesk/GLPI integration, let me know. I would be glad to test and report back with logs and results.

**Comment by paspo** [comment]
> How far along is this? I would live to test it's compatibility with GLPI. We use RustDesk here at my job, and I have been setting up GLPI for inventory in IT and it would be cool to be able to remote in with one click.

if you apply the modifications in this pr, you get  "one click open" support.

This PR is kept draft because rustdesk is transitioning towards flutter, rendering this useless.

> @paspo what do I setup in GLPI for it to grab the RustDesk ID from each PC? I cant seem to get it to.

GLPI agent is OK (https://github.com/glpi-project/glpi-agent/pull/193)
GLPI is also ready (https://github.com/glpi-project/glpi/pull/12406)

**Comment by rustdesk** [comment]
@Kingtous is working on this.

**Comment by rustdesk** [comment]
closed before @Kingtous has new PR.

**Pull request closed without merging**
