### PR TITLE
add minimize button on fullscreen toolbar

### PR DESCRIPTION
**Pull request by dignow**
1. Add minimize button on fullscreen toolbar.
2. Add tooltip of remote toolbar buttons.
3. Ignore window position that (x < -10000 || y < -10000).

https://github.com/rustdesk/rustdesk/discussions/5157

https://github.com/rustdesk/rustdesk/assets/136106582/d7f76374-0153-4b70-9e39-ec2c3e382665

### CODE REVIEW

**Comment by rustdesk** [comment]
But this minimize button looks very wierd.

**Comment by rustdesk** [comment]
Let's see how does teaviewer/anydesk handle this. We do not have to add this if can not find an elegant way.

**Comment by rustdesk** [comment]
> 3\. Ignore window position that (x < -10000 || y < -10000).

Also > 10000

**Comment by rustdesk** [comment]
> > 3. Ignore window position that (x < -10000 || y < -10000).
> 
> Also > 10000

add it,

**Comment by dignow** [comment]
https://github.com/rustdesk/rustdesk/assets/136106582/7796cdcd-817d-46c2-bc44-27a0bbdf31b0

**Comment by bauhuynhdev** [comment]
> aaax.mp4

I see you did a great job.

**Comment by rustdesk** [comment]
finish this first as we talked. move restore/min to below.

**Comment by dignow** [comment]
Use `Icons.remove` instead of `Icons.minimize`, because the `minimize` icon is too closed to the bottom.

```dart
TextButton(
            onPressed: () => widget.setMinimize(),
            child: Tooltip(
              message: translate('Minimize'),
              child: Icon(
                Icons.remove,
                size: iconSize,
              ),
            ),
          )
```


https://github.com/rustdesk/rustdesk/assets/136106582/bcc63358-7c31-4895-a7e4-4bfdb125579f

**Pull request merged**
