### PR TITLE
fix autofocus

### PR DESCRIPTION
**Pull request by grummbeer**
Fix autofocus for hostname in Settings | Network | proxy. 

Set cursor to "username" or "password", the focus goes back to "hostname"

### CODE REVIEW

**Comment by rustdesk** [comment]
Great, Thanks!

**Comment by rustdesk** [comment]
Go ahead please if you find more UI needed to be tweaked.

**Comment by grummbeer** [comment]
There are! How to handle? issue or PR(as draft)?

**Comment by rustdesk** [comment]
PR draft is good.

**Pull request merged**
