### PR TITLE
To support the touch pad of the magnetic keyboard on Android tablets.

### PR DESCRIPTION
**Pull request by lpcy**

### CODE REVIEW

**Comment by rustdesk** [comment]
reverted due to https://github.com/rustdesk/rustdesk/issues/4261#issuecomment-1534690442

**Comment by fufesou** [comment]
@lpcy For mobiles or tablets, the events are handled here.

Did you commit this PR for something was wrong on your devices?
Can you please help ensure if the handler is correct?

https://github.com/rustdesk/rustdesk/blob/357028b222d8973add39f07a333dad2b92c33b10/flutter/lib/models/model.dart#L1323


https://github.com/rustdesk/rustdesk/blob/357028b222d8973add39f07a333dad2b92c33b10/flutter/lib/mobile/pages/remote_page.dart#L463


https://github.com/rustdesk/rustdesk/blob/6643b8c830de31992b0f7a257d50cd94fa1d1314/flutter/lib/mobile/widgets/gestures.dart#L64

**Comment by lpcy** [comment]
The touchpad of my tablet device's magnetic keyboard is not available due to the event being ignored, so the above code has been added. Now that the code has been reverted, my touchpad is once again unusable @rustdesk @fufesou

**Comment by lpcy** [comment]
I am confused about ignoring events outside of the mouse in the code. It seems that the handling of events on the mobile end is quite complex. Is the mobile end still immature?Or are there other alternative solutions that I can use for testing?

**Comment by fufesou** [comment]
Sorry for late. I've read the code.

RustDesk only support one of physical mouse or touch pointer in one session.

https://github.com/rustdesk/rustdesk/blob/67d0ff4fe1bd46ec1c655481127394098b7d0b7b/flutter/lib/mobile/pages/remote_page.dart#L273

`events` in `getBodyForMobile()` are handled by the place you've modified.  
`events` in `getBodyForMobileWithGesture` are handled by `updatePan`.

https://github.com/rustdesk/rustdesk/blob/357028b222d8973add39f07a333dad2b92c33b10/flutter/lib/mobile/pages/remote_page.dart#L463

If you've ever connected a physical mouse or triggered `PointerHoverEvent.kind` as `PointerHoverEvent.kind.mouse`, RustDesk will set `isPhysicalMouse` to be `true`, thus it will not handle event on touch event.

Did you connected a physical mouse after connecting to the peer?

**Pull request merged**
