### PR TITLE
Updated rustdesk.json

### PR DESCRIPTION
**Pull request by VEER-TANMAY-SACHIN**
This PR should solve the problem of runtime.
/claim #5889
@sahilyeole

### CODE REVIEW

**Comment by sahilyeole** [comment]
@TouchstoneTheGreat Have you tested whether it has solved #5889 or not?

**Comment by TouchstoneTheGreat** [comment]
@sahilyeole No.
I am having some difficulty (hard) XO
If possible can you plz check
thenks mate XD

**Comment by rustdesk** [comment]
you need to test it for claiming the bounty.

**Comment by TouchstoneTheGreat** [comment]
@sahilyeole How do i build export flatpack build ?! I tried but it isn't working

**Comment by sahilyeole** [comment]
You can check the CI for building locally
https://github.com/rustdesk/rustdesk/blob/53cd259ffa21ac9c3b2d6a25ed088c6e0c4e000b/.github/workflows/flutter-build.yml#L1633
Or if you get stuck you can use github actions on your fork and run `Flutter Nightly Build` workflow, it will build releases.

**Comment by rustdesk** [comment]
Please give the new flatpak file to @ximex for confirmation.

**Comment by sahilyeole** [comment]
@TouchstoneTheGreat When you asked me to test, I ran the github workflow myself with the same changes as this PR.
The flatpak build is failing even after multiple re-runs. [Link to my workflow run](https://github.com/sahilyeole/rustdesk/actions/runs/6419351771)
So please try to build it locally first by following the CI.

**Comment by TouchstoneTheGreat** [comment]
@rustdesk it's not working.
@sahilyeole Thnks I'll figure it out

**Comment by rustdesk** [comment]
Very sorry, the bounty has been claimed.

**Comment by TouchstoneTheGreat** [comment]
If i have issues with whom i can discuss @rustdesk 
I solved the issue in overall 
workflows are assigned by maintainers of repo
The overall issue was solved !

**Pull request closed without merging**
