### PR TITLE
Skip anything after an # symbol in the filename.

### PR DESCRIPTION
**Pull request by madpilot78**
Windows renames files adding (1), (2) etc. before the .exe in case of duplicates, which causes the host or key values to be garbled.

This allows to protect from this adding a final "#" symbol to the filename.

### CODE REVIEW

**Comment by rustdesk** [comment]
#4162

**Comment by madpilot78** [comment]
I'm not sure I understand why this was reverted. #4162 is exactly the issue I was trying to fix. Is there some other reason why this cannot be included that I fail to see?

Any improvement I can make to this patch to make it acceptable?

**Comment by rustdesk** [comment]
Please communicate with the author of the issue.

**Comment by rustdesk** [comment]
Recover this please then. Sorry for my misunderstanding.

**Comment by rustdesk** [comment]
Not sure if the key will contain #. Here does not check #. https://github.com/rustdesk/rustdesk-server/blob/1f7d3fa05ce6c8b3198a29a4a5a8095419608fe3/src/common.rs#L132
You may need to submit a PR to rustdesk_server.

**Comment by madpilot78** [comment]
I don;t think a valid key can contain a `#`. Anyway there are various symbols a key can contain that windows will not allow in a filename, and in that case the documentation says to just generate a new key. The same can be done for the `#` symbol.

The server does not need to know anything about this.

**Pull request merged**
