### PR TITLE
[feat] x11 clipboard copy and paste file

### PR DESCRIPTION
**Pull request by ClSlaid**
This PR shall offer rustdesk ability to copy files on Linux.

Part of OSPP 2023.

Working in progress.

X11 only, Wayland is not planned.

### CODE REVIEW

**Comment by rustdesk** [comment]
@fufesou

**Comment by dignow** [comment]
There are some unexpected things.

1. There's not "Allow file copy and paste" option in the remote toolbar menu.
2. File copy failed. It report the local path cannot be found.
3. File copy & paste can only be recognized when files on both side is in the desktop dir.


https://github.com/rustdesk/rustdesk/assets/136106582/d1500beb-4ade-4e6c-a2df-19364cd78e4e


https://github.com/rustdesk/rustdesk/assets/136106582/9340d7fb-e925-4cf3-96ae-0275437b6cb8

**Comment by ClSlaid** [comment]
> There are some unexpected things.
> 
> 1. There's not "Allow file copy and paste" option in the remote toolbar menu.
> 2. File copy failed. It report the local path cannot be found.
> 3. File copy & paste can only be recognized when files on both side is in the desktop dir.

Thanks for your kindly trials and videos!

This PR is still in progress and I've just made it compile when I open it.

File copy should not work now. That's because paths passing to clipboard are not prefixed with FUSE mount point. Unfortunately, you are making a local copy paste and no transfer occured.

And FUSE code is not tested, for now.

**Comment by ClSlaid** [comment]
Managed to made it work (Linux to Linux), though really slow and high CPU usage.

图片

**Comment by rustdesk** [comment]
Try to find out the bottleneck.

**Comment by ClSlaid** [comment]
Marked to draft due to compilation on other platforms is untested.

**Comment by fufesou** [comment]
@ClSlaid Hi, did you commit everything? I can't compile it.

`0VS3ABU%LJKO $NPLSAT73

W_OP8Q4Q0@9VV1G0OI1 H7

**Comment by ClSlaid** [comment]
Please make sure you updated your rust toolchains to the latest stable/nightly and installed dependencies:

- fuse3
- xdotool
- libX11
- libxcb

**Comment by fufesou** [comment]
I'll try, but the error seems to be a limitation of the rust compiler and has nothing to do with the libraries used.

**Comment by fufesou** [comment]
I've compiled successfully on another PC using rustc version 1.72.1.

**Comment by ClSlaid** [comment]
cc @fufesou
I've added a commit fixing nautilus file copying/pasting. Nautilus does not accept `text/uri-list` and `x-special/gnome-copied-files` from other applications now, and they copy against each other using `application/vnd.portal.files`. Yet, thankfully, it still accepts `x-special/nautilus-clipboard`.

I guess copying to desktop might also go through that portal. But supporting it will make this PR too large to review.

**Comment by rustdesk** [comment]
How about the progress of this PR now?

**Comment by ClSlaid** [comment]
Just purged `arboard` under `Linux`. X11's text clipboard is always polluted by file URIs and when setting text clipboard file URIs will also get erased.

**Comment by ClSlaid** [comment]
cc @rustdesk 
Is this PR acceptable for master branch now?

**Comment by fufesou** [comment]
I'm still testing.
I will give the results here after the test is completed.

**Comment by fufesou** [comment]
@ClSlaid There're still some issues.

1. Text copy & paste no longer works. (I'll test if the original text copy & paste works.)
2. Copy & paste sometimes gives an error.
3. The connection may be interrupted when copy & paste error occurs.
4. Sometime it take a long time to wait the pasting, then report error.

https://github.com/rustdesk/rustdesk/assets/13586388/3f678207-b9e6-498c-9363-8b00a75c2a86

https://github.com/rustdesk/rustdesk/assets/13586388/165d973a-eaf9-490d-a12d-df4cdb268bd5

**Comment by ClSlaid** [comment]
>     1. Text copy & paste no longer works. (I'll test if the original text copy & paste works.)

Sorry for not covered this bug, just fixed. This was caused by the short-living of clipboard process. Fixed by wrapping it in `OnceCell`.

Adjusted the algorithm of loading local files, now the transfer speed is doubled.

图片
Just tested copying a directory containing many symlinks, deep hierarchies and small files (node_modules) and worked well. I can also paste text when copying files.

Would you like to fire another test? cc @fufesou.

**Comment by fufesou** [comment]
No more error dialog reports.
But sometimes the file cannot be pasted.


https://github.com/rustdesk/rustdesk/assets/13586388/5cdfa8d3-a63f-4102-af25-05c382663a3d


https://github.com/rustdesk/rustdesk/assets/13586388/cf10975a-c423-4bdd-bbf6-9da9e496f784

**Comment by fufesou** [comment]
It seems almost complete and I'm ready to move on to testing the others.

- [ ] Text copy&paste, desktop version.
- [ ] Win -> Win, file copy&pate.
- [ ] Installed version, test agin.

**Comment by ClSlaid** [comment]
Strange, when screen recording, the x11 clipboard gets unstable.

**Comment by ClSlaid** [comment]
I've managed to get file copy & paste to work on macOS, shall I start another PR or merge that to this PR?

Example: linux (flutter run -d linux --release) ==> macOS (cargo run with sciter)

图片

**Comment by fufesou** [comment]
https://github.com/rustdesk/rustdesk/assets/13586388/1b94826e-3b96-446a-8628-d08e50c6eb97

**Comment by ClSlaid** [comment]
Hi @fufesou, almost all error we encounter in copy & paste file is clipboard timeout. I had once written a dead lock bug with dependency's wait function, and by using time limited API the bug was then solved.

The problem should now be solved since I make the client used for file copying & pasting wait forever. It will keep waiting unless the data was available.

**Comment by fufesou** [comment]
There's a CI issue.

RustDesk use Ubuntu18.04 as the build OS, But `libfuse` requires at least Ubuntu 20.04.

macOS has the same issue.

O_DMM0E_14_(RYKS~O_Y%EX

**Comment by ClSlaid** [comment]
1. so cannot we upgrade to Ubuntu 22.04 or newer version? I remembered that Ubuntu 18.04 LTS is not officially supported now?
2. maybe try `brew install macfuse` instead of `brew install osxfuse`?

**Comment by rustdesk** [comment]
> 1. claimed to support libfuse2, maybe give it a try?

Yes

**Pull request merged**
