### PR TITLE
res/vcpkg: Bump aom to 3.9.1, opus to 1.5.1 and libvpx to 1.14.1

### PR DESCRIPTION
**Pull request by basilgello**
Attempt to build with latest ports

### CODE REVIEW

**Comment by basilgello** [comment]
@rustdesk can you please kick artifact build so I dont have to build debs myself for test? :)

**Comment by rustdesk** [comment]
How to kick? :(

**Comment by basilgello** [comment]
Trigger nightly build just like you did when we did vcpkg deps. The artifacts will go nightly and I can deplly them quickly to test Debian -> Debian, Debian -> Android, Android -> Debian

**Comment by rustdesk** [comment]
Triggered, https://github.com/rustdesk/rustdesk/actions/runs/9741792416

**Comment by basilgello** [comment]
Cool - ios apk build complaints for undefined symbols but the schefuled nightly build 10 hours ago has the same error. Might be related to https://github.com/flutter/flutter/issues/139024

**Comment by basilgello** [comment]
@rustdesk All tested variants work on my side

**Comment by rustdesk** [comment]
Good job.

**Comment by basilgello** [comment]
This one can be merged. Afterwards, please run fdroid.yml workflow so version file is generated. After that I will PR the fdroid change

**Comment by basilgello** [comment]
@rustdesk ^^ ;)

**Comment by basilgello** [comment]
Cool! The only thing I need now from you is to start fdroid workflow (the one you restored back) so the version file gets created

**Comment by basilgello** [comment]
And once I get it I will push MR to fdroid ;)

**Comment by rustdesk** [comment]
but fdroid trigger by tag creation. What will happen if I run it manually?

**Comment by basilgello** [comment]
When run manually it will create the version file with latest tagged release, i.e `1.2.6`. It is fine for me because I will add vcpkg change as fdroid patch but I can not fix versionfile URL in fdroiddata if it does not exist

**Comment by basilgello** [comment]
And once you tag 1.2.7 it will redo versionfile and in turn fdroid updater will hook it up

**Comment by basilgello** [comment]
Version file got updated but the contents is `master` not `1.2.6`. Let me investigate one quickly and PR the fix

**Comment by rustdesk** [comment]
This way is not good, you can fetch latest release via https://github.com/rustdesk/rustdesk/releases/latest

**Comment by basilgello** [comment]
Thanks, I think it is the best way given you tag prereleases as prereleases and prereleases do not land up as latest

**Comment by rustdesk** [comment]
preleases never appear as latest.

**Comment by rustdesk** [comment]
Could you please check the two CI failures, https://github.com/rustdesk/rustdesk/actions/runs/9772869224

**Comment by basilgello** [comment]
Moment

**Comment by basilgello** [comment]
It looks like opus 1.4 is being used because I dropped local port but vcpkg baseline needs to be updated: https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/flutter-build.yml#L26 and https://github.com/rustdesk/rustdesk/blob/master/.github/workflows/playground.yml#L20

**Comment by basilgello** [comment]
Well, the local port should be reinstated to 1.5.1 as vcpkg maintainers did not merge my PR fixing exactly this build issue. And I thought they did :(

**Comment by basilgello** [comment]
Ah wait, no they have it merged but rewritten in some subsequent commit… So the baseline should be bumped - let me PR one

**Pull request merged**
