### PR TITLE
Refact/msi more install options

### PR DESCRIPTION
**Pull request by fufesou**
1. Fix silent repair/upgrade error. `msiexec /i package.msi /qn` will cause incomplete installation.   
On other computers, this issue may even result in two versions, `1.3.0.1` and `1.3.0.2`, coexisting. The only workaround before the repair was to avoid "repair/upgrade" and instead just uninstall and then install.

https://github.com/user-attachments/assets/a356eb4f-300d-4051-9be6-980ad53a3866

https://github.com/user-attachments/assets/2537af4e-1ffc-4623-a534-af6e6f2b8dff

2. Add install options.

https://github.com/rustdesk/rustdesk/discussions/8829

https://github.com/user-attachments/assets/847d2851-3eba-41eb-9bf4-a23130deb2ae

https://github.com/user-attachments/assets/a04e5c86-8a84-4b14-99d2-054721e6c7a6

The options `CREATESTARTMENUSHORTCUTS` and `CREATEDESKTOPSHORTCUTS` support `1/0` or `Y/N`.

```
msiexec /i Package.msi /qn INSTALLFOLDER="D:\Program Files\RustDesk" CREATESTARTMENUSHORTCUTS="0" CREATEDESKTOPSHORTCUTS="1" /l*v install.log

msiexec /i Package.msi /qn INSTALLFOLDER="D:\Program Files\RustDesk" CREATESTARTMENUSHORTCUTS="N" CREATEDESKTOPSHORTCUTS="Y" /l*v install.log
```

**Priority:** 
```
UI (command line) > Previous options (registry values) -> Default values
```

### CODE REVIEW

**Comment by rustdesk** [comment]
> CREATESTARTMENUSHORTCUTS="0" CREATEDESKTOPSHORTCUTS="1" 

Can not use 'Y' / 'N'?

**Comment by rustdesk** [comment]
> When upgrading, previous installation options cannot be read correctly.
INSTALLFOLDER no problem?

**Comment by fufesou** [comment]
> > CREATESTARTMENUSHORTCUTS="0" CREATEDESKTOPSHORTCUTS="1"
> 
> Can not use 'Y' / 'N'?

I'll use `'Y' / 'N'`.


> > When upgrading, previous installation options cannot be read correctly.
> 
> INSTALLFOLDER no problem?

`INSTALLFOLDER` also has the same problem. I'm still looking for the reason.

**Comment by fufesou** [comment]
> > CREATESTARTMENUSHORTCUTS="0" CREATEDESKTOPSHORTCUTS="1"
> 
> Can not use 'Y' / 'N'?

I'll support both `1/0` and `Y/N`, because `1/0` is already supported. Maybe someone is using it.

**Pull request merged**
