### PR TITLE
vcpkg deps

### PR DESCRIPTION
**Pull request by basilgello**
- Ignore CRLF/LF conversion on sciter patch apply

### CODE REVIEW

**Comment by basilgello** [comment]
Lets try? :)

**Comment by rustdesk** [comment]
not stable https://github.com/rustdesk/rustdesk/actions/runs/6864600994/job/18666741043

**Comment by basilgello** [comment]
Strange. I upstreamed all changes to vcpkg including libvpx and this one. They are gradually approved but none are merged as of today. Once they are merged, we can use vcpkg ports :)

**Comment by rustdesk** [comment]
Nightly build failed very day is embarrassing.

**Comment by basilgello** [comment]
I will push another PR changing the patch encoding to LF. This should solve thr error until upstrram changr gets merged.

**Pull request merged**
