### PR TITLE
add Belarusian locale

### PR DESCRIPTION
**Pull request by stmc**

### CODE REVIEW

**Comment by rustdesk** [comment]
Thanks

**Comment by rustdesk** [comment]
You also need to modify https://github.com/rustdesk/rustdesk/blob/master/src/lang.rs to make it take effect.

**Comment by stmc** [comment]
Done

**Comment by rustdesk** [comment]
Thanks, you have some errors, https://github.com/rustdesk/rustdesk/actions/runs/9678459302/job/26702301339?pr=8480

**Pull request merged**
