### PR TITLE
Update nl.rs

### PR DESCRIPTION
**Pull request by RijckAlex**

### CODE REVIEW

**Comment by rustdesk** [comment]
@FastAct could you please review?

**Comment by rustdesk** [comment]
@AnonymousWP you please review?

**Review by AnonymousWP — CHANGES_REQUESTED** [review]
@RijckAlex Both are correct, though "geslaagd" seems to sound a bit literally translated. Maybe we can add "van".

**Comment by RijckAlex** [comment]
Former @Fastact account changed to @RijckAlex for private reasons

**Review by RijckAlex — COMMENTED** [review]
Importeren serverconfiguratie geslaagd        is good
Importeren serverconfiguratie  is geslaagd    is better
Exporteren serverconfiguratie geslaagd         is good
Exporteren serverconfiguratie is geslaagd      is better
Notification: Former @Fastact account changed to RijkAlex for private reasons (retired)

**Comment by AnonymousWP** [comment]
Alright, please add it and I'll approve.

**Review by AnonymousWP — APPROVED** [review]

**Pull request merged**
