### PR TITLE
[feat] osx/clipboard file

### PR DESCRIPTION
**Pull request by ClSlaid**
Copy & paste file implementation on macOS.
图片

Depends on #5638

### CODE REVIEW

**Comment by ClSlaid** [comment]
> I have merged https://github.com/rustdesk/rustdesk/pull/5638, but seems this PR is not clean. The code change is not based on https://github.com/rustdesk/rustdesk/pull/5638.

this branch is actually a fork of that pr since commit: 2bb1310094674616594992a79cdff41e5432cfe6

and i've backported the changes in that pr in the last merge commit.

**Comment by rustdesk** [comment]
> and i've backported the changes in that pr in the last merge commit.

Yes，please

**Comment by rustdesk** [comment]
A new PR is better.

**Comment by ClSlaid** [comment]
> A new clean PR is better.

Ok, I'll reopen a new PR for this.

**Pull request closed without merging**
