### PR TITLE
vcpkg: sort triplets and restore local opus port for 1.5.1

### PR DESCRIPTION
**Pull request by basilgello**
- **ci/flutter-build: Sort out triplets in job matrices**
- **Restore local port for opus 1.5.1**

### CODE REVIEW

**Comment by basilgello** [comment]
Lets try this one @rustdesk ^^

**Comment by rustdesk** [comment]
Thank you very much, all work now.

**Comment by basilgello** [comment]
I am still confused with `flutter/build_android.sh`, `flutter/build_ios.sh`, `flutter/ios_arm64.sh`, `flutter/ios_x64.sh`, `flutter/run.sh`. They duplicate steps in `.github/workflows/flutter-build.yml` but are used nowhere. Maybe it is better to consolidate them just like I did with `flutter/build_android_deps.sh` and call them in CI yaml so there is no need to fix same things here and there?

**Comment by basilgello** [comment]
@rustdesk ^^ Thinking of re-organizing build steps and moving f-droid build step into this tree :)

**Pull request merged**
