### PR TITLE
refactor dialog

### PR DESCRIPTION
**Pull request by fufesou**
Mainly move dialogs from `mobile` path to `common` path.

### CODE REVIEW

**Comment by rustdesk** [comment]
@grummbeer do you have any idea about this dialog design which is login to headless linux? Different from normal login, remote linux user/password is required for headless linux. I still think current dialog does explain clearly, the users can be confused by the additonal user name and password.

**Comment by grummbeer** [comment]
https://github.com/rustdesk/rustdesk/blob/9ec0b4be56f04eb315ae1e8ada398a3e7eb49acb/flutter/lib/common/widgets/dialog.dart#L544


both sides are the same

**Comment by rustdesk** [comment]
> https://github.com/rustdesk/rustdesk/blob/9ec0b4be56f04eb315ae1e8ada398a3e7eb49acb/flutter/lib/common/widgets/dialog.dart#L544
> 
> both sides are the same

@fufesou

**Comment by rustdesk** [comment]
> On the first glace, the message from toolip could placed directly obove the system login to avoid question marks.

Yes, @fufesou place on the. dialog directly with small font compared with title, and change title to original one (before this PR). You even do not put a big question mark there, no guys know moving mouse there to show a tooltip.

**Comment by rustdesk** [comment]
and this seperate is not eye-catching enough, when I say put a seperator there, you should have some thinking also, not just for finishing an assigned job.

image

**Comment by grummbeer** [comment]
According to material https://m3.material.io/components/dialogs/guidelines#fb75c64c-81c1-45ea-b97b-eb0bcb4c5dc9

The headline should smaller and a kind of heading/description goes to both sections. Section 1. Login to system, section 2. Login to rustdesk.

**Comment by rustdesk** [comment]
> Section 1. Login to system, section 2. Login to rustdesk.

Yes, @fufesou

**Comment by rustdesk** [comment]
Seperator line can be remove if so, I think.

**Comment by grummbeer** [comment]
> Seperator line can be remove if so, I think.

yes separation made by heading.

**Comment by grummbeer** [comment]
sorry if this is a stupid question but …

https://github.com/rustdesk/rustdesk/blob/12a5a7cf8c277dabe02b197c227cf7c51e814ba1/flutter/lib/common/widgets/dialog.dart#L499-L509

`final username` and `final password` not used due commented out in login() arguments.

1. What happen with them on submit?

2. Can you clarify the situation with a comment? or similar
   It is irritating when stumple upon such situations because it is not clear what is intended. Just a forgotten test? Something unfinished? Wanted as hint for later work? Can it be saftly removed? Or going the save way and leaveing it untouched to prevent the author from being pissed?

**Comment by fufesou** [comment]
> `final username` and `final password` not used due commented out in login() arguments.

They should be sent to the controlled side. These variables are keet here for the near future work.

**Comment by grummbeer** [comment]
Thank you for the clarification!

**Pull request merged**
