### PR TITLE
feat: dual audio transmission support

### PR DESCRIPTION
**Pull request by Kingtous**
related: #188

This PR is working on make dual audio transmission possible.

- [x] multi-instance audio service for dual audio transmission.
- [x] add dual transmission protocol.
- [x] fit for audio playing on both of host and server side.
- [x] tested on the cases below
    - [x] Windows ---(controls)--> macOS 
    - [-] [Working on] macOS ---(controls)--> Linux, loop back is not working yet
    - [x] Linux ---(controls)--> macOS 
- [x] add ui selection
    - [x] sciter
    - [x] flutter 

This PR adds an option to enable dual audio transmission now. After switching to `dual way` of audio transmission, the input device will automatically set to the default speaker.

image

### CODE REVIEW

**Comment by test2a** [comment]
So excited about this.....


Could this by any chance be modified to have video as well?

We can imagine like have a floating video widget showing your own and other side cameras...

**Comment by rustdesk** [comment]
> So excited about this.....
> 
> Could this by any chance be modified to have video as well?
> 
> We can imagine like have a floating video widget showing your own and other side cameras...

no for short term

**Comment by rustdesk** [comment]
@test2a please test and feedback.

**Comment by test2a** [comment]
@rustdesk nightly seems to be 4 hours old so should i download that or wait for new build?

**Comment by rustdesk** [comment]
Thanks, it will be ready tommorrow.

**Comment by rustdesk** [comment]
I can trigger it now, will be ready soon.

**Pull request merged**
