### PR TITLE
Update logo in README

### PR DESCRIPTION
**Pull request by rakleed**
To make it look good in a dark theme, I removed the light bright background.

### CODE REVIEW

**Comment by rustdesk** [comment]
But it looks ugly for me without light background in dark theme. Sorry, i can not accept your proposal.

**Comment by rakleed** [comment]
@rustdesk what exactly is the problem? Looks good to me.

Screenshot 2023-02-16 at 18 14 26

**Comment by rustdesk** [comment]
I still think old is better, with better contact.

**Comment by rustdesk** [comment]
the blue gradient color looks strange on black background.

**Comment by rustdesk** [comment]
it is my opinion. we can make a poll on the girhub discussions. let users decide.

**Comment by rakleed** [comment]
The problem is that for a dark theme, a light background is a bad solution, as it is not pleasant for the eyes if you are in a dark room.

You can also just reduce its background to about the size of a square, but it seems that it will look strange.

**Comment by rakleed** [comment]
> it is my opinion. we can make a poll on the github discussions. let users decide.

Sounds good.

**Comment by rustdesk** [comment]
could you write a poll post?

**Comment by rakleed** [comment]
Yes, sure. But I'll do it a little later.

**Comment by rakleed** [comment]
@rustdesk and what do you think about such option: https://github.com/rakleed/rustdesk/tree/patch-1#readme?

**Comment by rustdesk** [comment]
> @rustdesk and what do you think about such option: https://github.com/rakleed/rustdesk/tree/patch-1#readme?

Looks wierd.

**Comment by rakleed** [comment]
@rustdesk if the last option is suitable, then you can reopen the PR and accept it.

**Comment by rustdesk** [comment]
I still prefer our original one than your last option.

**Comment by rustdesk** [comment]
@grummbeer @ NicKoehler how do you think about his proposals?

**Comment by NicKoehler** [comment]
As a dark theme user I still like the old one more, the only thing that bother me is the font and colors..
I like something like this:

immagine

**Comment by grummbeer** [comment]
haven't a bulletproof opinion for now.

i am also a dark mode user and yes, scrolling over the readme makes a bit a flash light

> the blue gradient color looks strange on black background.

can also see this, and the "Your remote desktop" loses contrast.

How about just reducing the brightness of the surrounding area? Maybe some transparency and the dark background will tone down the brightness.

check the alt tag: "RustDesk - Dit fjernskrivebord"?

**Comment by rustdesk** [comment]
i am dark theme user on mac, and white theme user on win.

**Comment by rustdesk** [comment]
Close since no consensus.

**Pull request closed without merging**
