### PR TITLE
Fix. Text Copy&Paste on Linux is unstable

### LINKED ISSUE #6859: Copy Paste not working in one direction (Remote -> Local)
### Bug Description

Running nightly on both machines, I can copy paste from my local machine to the remote machine but not in the other direction.

I've enabled/disabled clipboard on both, rebooted, and no change. 

File copy from Remote to local is working

no data in my logs for rustdesk to indicate any issues, any way to make it more verbose ?

### How to Reproduce

Remote into computer
Select text on remote computer
Press ctrl+C
Focus to local computer
Press ctrl+V
No text pasted, or previous clipboard from local pasted

### Expected Behavior

Clipboard should transfer text to local machine

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

n/a

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by fufesou**
This PR may fix https://github.com/rustdesk/rustdesk/issues/6859 on Linux platform.

### Issue

`arboard` uses a fixed duration(10ms) as the timeout for x11 connection. 

https://github.com/1Password/arboard/blob/77e0e078eb460ac2fa0eda96124163c11ef6b2d1/src/platform/linux/x11.rs#L142

But for RustDesk, sometimes it needs about 20ms or more to connect x11.

So the text clipboard is not stable.

And if the following line fails, the "copy & paste" from client to host will not work anymore in that connection.

https://github.com/rustdesk/rustdesk/blob/7b317619acdf26853e05c5e398f5bdc19fee776c/src/client.rs#L726 

### Fixed 

In this PR, retry and increasing timeout are added for `new()` and `get_text()`.

```rust
        for i in 1..4 {
            arboard::Clipboard::set_x11_server_conn_timeout(dur * i);
            match arboard::Clipboard::new() {
                Ok(c) => return Ok(ClipboardContext(c)),
                Err(arboard::Error::X11ServerConnTimeout) => continue,
                Err(err) => return Err(err.into()),
            }
        }
        bail!("Failed to create clipboard context, timeout");
```

PR for `arboard` is also submitted.

### CODE REVIEW

**Comment by rustdesk** [comment]
Did you reproduce this timeout?

**Comment by rustdesk** [comment]
The OP is windows <-> windows

**Comment by fufesou** [comment]
> Did you reproduce this timeout?

Yes, I've print the time. Sometimes it takes more than 20ms to setup the clipboard context on x11.

> The OP of the issue is windows <-> windows

I could not reproduce Win <-> Win.

There's also issues Ubuntu <-> Ubuntu/Win in the following post.

**Comment by fufesou** [comment]
I'll try to find out why Win <-> Win fails sometimes.

**Pull request closed without merging**
