### PR TITLE
Try to detach /opt/artifacts from sciter

### PR DESCRIPTION
**Pull request by basilgello**
Signed-off-by: Vasyl Gello <vasek.gello@gmail.com>

### CODE REVIEW

**Comment by basilgello** [comment]
@rustdesk

**Comment by rustdesk** [comment]
don`t you have arm64 to test?

**Comment by basilgello** [comment]
arm64 but 64-bit only :( And the onlty runner that can do armhf has no root access for me :(

**Comment by rustdesk** [comment]
acutally our runner is on arm64 (64-bit) also.

**Comment by basilgello** [comment]
Is it qemu? Because what I managed to find is old AMD Opteron (Seattle arch) that does armhf and aarch64. But no r00t so have to use proot.

**Comment by rustdesk** [comment]
yes, arm32 runs on docker qemu of an arm64 host.

**Pull request merged**
