### PR TITLE
Fix/desktop touchpad scale

### PR DESCRIPTION
**Pull request by dignow**
1. Add pointer device event. Superset of mouse and touch event.
2. Support zoom of touchpad and touchscreen on desktop. (Win only)

Zooming is simulated by "Ctrl" + "mouse scroll" on Windows.

TODOs:
- [ ] Merge mouse event to pointer device event.
- [ ] Scale on Linux and macOS ?

### CODE REVIEW

**Comment by rustdesk** [comment]
> 2\. Scale on Linux and macOS ?

Yes

**Comment by rustdesk** [comment]
Does this fix https://github.com/rustdesk/rustdesk/issues/3744?

**Comment by fufesou** [comment]
Yes. For windows as the controlled side, both scale and pan work.

**Comment by rustdesk** [comment]
Not working on Mac?

**Comment by fufesou** [comment]
> Scale on Linux and macOS ?

Two-fingers scaling on touchpad still does no work on Linux and MacOS.

**Comment by rustdesk** [comment]
Pan ok?

**Comment by fufesou** [comment]
No, scroll works. Pan is not supported for now. Shall I do it now?

**Comment by fufesou** [comment]
Pan is ok for Windows as the controlled side.
For Linux and MacOS, only scroll is ok..

**Comment by rustdesk** [comment]
Scroll is enough for now.

**Comment by rustdesk** [comment]
https://github.com/rustdesk/rustdesk/issues/3744 is related to scroll and zoom using Mac as controlling side.

**Comment by fufesou** [comment]
Sorry for misunderstanding of pan. I throught it was horizontal scroll.

Pan is not supported for touchpad.

Vertical and horizontal scroll are supported on Windows.
Only vertical scroll is supported on MacOS.

**Comment by fufesou** [comment]
Ignore what I said above.

Vertical and horizontal scroll are already supported on Windows, Linux, MacOS.

**Pull request merged**
