### PR TITLE
fix compile fail when use cli feature

### PR DESCRIPTION
**Pull request by chamgin**
there are compile error when use cli feature:
1. rpassword:: read_password_from_tty need change, https://docs.rs/rpassword/6.0.0/rpassword/index.html
2. no implement Interface send
3. can't use make_fd which implement on ui module

### CODE REVIEW

**Comment by rustdesk** [comment]
Thanks, please do not use sciter in common.rs, because it should be independent of ui sdk. we are removing sciter.

**Comment by chamgin** [comment]
邮件已收到，谢谢！

**Comment by chamgin** [comment]
> Thanks, please do not use sciter in common.rs, because it should be independent of ui sdk. we are removing sciter.

yes i moved it from common to client/helper

**Comment by rustdesk** [comment]
sorry, helper.rs should also be ui sdk independent.

**Comment by rustdesk** [comment]
@Kingtous https://github.com/rustdesk/rustdesk/blob/7c2db5a83559ed9190abc5ceb717983d6fc15cff/src/client/file_trait.rs#L13 we do need refactor this part of code

**Comment by rustdesk** [comment]
> test

Thanks

**Comment by rustdesk** [comment]
@chamgin could you try out https://github.com/rustdesk/rustdesk/pull/724?

**Comment by chamgin** [comment]
> @chamgin could you try out #724?

yes, it works, no need my commit. i just make some product test

**Comment by chamgin** [comment]
邮件已收到，谢谢！

**Pull request closed without merging**
