### PR TITLE
refact: macos, hide&show on leaving view

### PR DESCRIPTION
**Pull request by fufesou**
Try workaround https://github.com/rustdesk/rustdesk/issues/8548

No side effects are found.

https://github.com/user-attachments/assets/ae2fb31b-c220-4000-89a6-a56e2ceb58d3

### CODE REVIEW

**Comment by zhangbo8418** [comment]
Thanks, it seems to be working, but more testing is needed. The Android TV remote control is also broken. Now the remote control cannot press confirm. Can it be repaired?

**Comment by rustdesk** [comment]
picture? 1.2.6 works?

**Comment by zhangbo8418** [comment]
> picture? 1.2.6 works?


There was a version that worked before, but I forgot which version it was.

**Comment by rustdesk** [comment]
> it seems to be working

@zhangbo8418 it fixed your freezing. Still working today?

**Comment by zhangbo8418** [comment]
> > it seems to be working
> 
> @zhangbo8418 it fixed your freezing (#8548). Still working today?


I have a MacBook Pro 2019 here, and I tested it again. It doesn’t work, but sometimes it does, so I said I need to test more.

**Comment by rustdesk** [comment]
@fufesou add more hide/show

**Comment by rustdesk** [comment]
@zhangbo8418 in what case it will freeze in your case?

**Comment by zhangbo8418** [comment]
> @zhangbo8418 in what case it will freeze in your case?


It's just weird, I don't know why, it just works sometimes and sometimes it doesn't. . .

**Comment by fufesou** [comment]
@zhangbo8418 Hi, can you please send me an email? linlong1266@gmail.com

**Comment by rustdesk** [comment]
fuesou will look into your android tv broken issue also.

**Comment by zhangbo8418** [comment]
> @zhangbo8418 Hi, can you please send me an email? [linlong1266@gmail.com](mailto:linlong1266@gmail.com) It might be more convenient for us to communicate directly.

I know how to make it work.

https://github.com/user-attachments/assets/33235f2f-8eed-4836-bac8-50a8888e3573

**Comment by rustdesk** [comment]
What you have done will trigger hide/show. So we need to add more hide/show.

**Comment by zhangbo8418** [comment]
> What you have done will trigger hide/show. So we need to add more hide/show. Add hide/show to windows focus event. @fufesou

I didn't pay attention at first, I just felt that sometimes it worked and sometimes it didn't work. It turned out that I just opened the browser and it worked.

**Comment by rustdesk** [comment]
Thanks very much, this helps us a lot.

**Comment by rustdesk** [comment]
@zhangbo8418 could you help test the newest nightly build?

**Comment by zhangbo8418** [comment]
> @zhangbo8418 could you help test the newest nightly build? We put a new workaround half hour ago.

Useless

**Comment by fufesou** [comment]
Thanks for your feedback.
I'm trying to download and install a VM, then maybe I can reproduce it.

**Comment by rustdesk** [comment]
@zhangbo8418 could you help confirm what time point it starts to freeze, leave view, lose focus, or gain focus? you can open a video in rustdesk (disable texture rendering).

**Comment by rustdesk** [comment]
@zhangbo8418 Could you tes the newest nightly build? we put a fix.

**Pull request merged**
